### ISSUE TITLE
Multiple configurations for both mobile and desktop

### ISSUE THREAD

**Issue by ltpquang** [qaprosoft/carina#1000]
We are currently setting up Carina for running our mobile clients' tests, including iOS, Android and web app.

As suggested in qaprosoft/carina-demo#48, we intend to leave **configs.properties** blank, and use separated configuations files for each testing device. Then we will pass the configuration file name to the test and use `CapabilitiesLoader` to load the appropriate capabilities.

This approach works, but we need to workaround a bit to bypass the `MobileFactory`'s `Configuration.getPlatform()` call, since it doesn't load the platform name from our custom capabilities.

Moreover, using separate config files makes the shared configs between platform (Selenium host, Jira host, Environment config...) duplicated over and over again, which is not good.

So what is the proper way for such a situation like this? Can we have a shared config file for all the platforms, and another extra config file for each of them?

**Comment by vdelendik** [comment]
adjusted Configuration.getPlatform() to pay attention to capabilities platform and platformName:
https://github.com/qaprosoft/carina/pull/1004

changes can be tested using 6.4.793-SNAPSHOT carina build

**Comment by vdelendik** [comment]
merged to master: https://github.com/qaprosoft/carina/commit/75b36b8a5e664af99bda7900db262aa29a38e42b
