### ISSUE TITLE
Add ability to choose what strategy for element loading to use

### ISSUE THREAD

**Issue by SergeiZagriychuk** [qaprosoft/carina#1010]
Right now by default when you interact with web elements carina first of all checks that element presents in page DOM and only then completes required action.
But for web automation it's more reasonable to check visibility of web element before action. Because right now we regularly face failures when element presents in DOM but not visible and due to that action attempt sometimes fails.
We need ability to choose what loading strategy to use by default.

**Comment by vdelendik** [comment]
6.4.36-SNAPSHOT+
it seems like released build will be 6.5.36+
