### ISSUE TITLE
replace hub_mode by optional capabilities.provider 

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1021]
we have to remove enum which potentially lead to compilation failure and replace it's logic by optional capabilities.provider filed value.

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/carina/pull/1106
6.4.41-SNAPSHOT

Test scenario: workable environment with selenium, mcloud, zebrunner and browserstack account. 
Using overrideFields provide required capabilities.provider value and 6.4.41-SNAPSHOT carina.
And execute web/mobile tests using appropriate provide hub. Based on actual value corresponding url should be used by pipeline

**Comment by okamara** [comment]
Verified. Fixed.
