### ISSUE TITLE
Rerun failed tests doesn't work as expected

### ISSUE THREAD

**Issue by vrudyk** [qaprosoft/carina#1042]
**Description**
User has test run with failed tests. After tapping on rerun only failures, only few tests rerun.
For example: user have 120 failed tests, rerun only failures started with only 6 tests, not 120.

**Steps to reproduce**

1. Go to list with test runs.
2. Select test run with failed tests. Click rerun only failures.

**Actual behavior**
Not all failed tests rerun. 

**Expected behavior**
Only failed tests rerun.

**Environment**
CARINA_CORE_VERSION: 6.4.36

**Comment by vdelendik** [comment]
hotfix can be teted with 6.4.846-SNAPSHOT core build

**Comment by vdelendik** [comment]
closing as fixed indirectly
