### ISSUE TITLE
Add params to Carina User Guide

### ISSUE THREAD

**Issue by okamara** [qaprosoft/carina#1045]
**Describe the solution you'd like**

The list of params that possible to add:
*  uiLoadedMarker for your page. that is regular ExtendedWebElement when (if set) is used for validating of Page loading status by method isPageOpened() or assertPageOpened(). Use setUiLoadedMarker() at your pages to set it up
* assertPageOpened() method was introduced. no need to write description for Assert failures in isPageOpened() assertions anymore
* assertUIObjectPresent() and assertUIObjectNotPresent() methods were introduced in AbstractUIObject class
* element_loading_strategy config parameter was introduced. by default it's set to BY_PRESENCE_OR_VISIBILITY value. that means carina waits for appearance of web elements in page DOM model or their visibility. In some cases condition with presence happens faster but elements are still not accessible due to invisibility at this short period of time. that how it worked in previous carina versions. for web automation I'd recommend to override this parameter to element_loading_strategy=BY_VISIBILITY In that case carina will proceed only after web element is displayed on the page
* waitForJSToLoad() method was introduced in AbstractPage class. it uses JS under the hood and helps to wait till all dynamic web elements on the page are getting loaded

**Comment by DimaGrinevich** [comment]
includes this issue https://github.com/qaprosoft/carina/issues/1074

**Comment by DimaGrinevich** [comment]
Need to check for language mistakes and text format
http://qaprosoft.github.io/carina/automation/web/#element-loading-strategy in element loading strategy

**Comment by okamara** [comment]
Verified. Done.
