### ISSUE TITLE
unable to capture screenshot for one more error

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1046]
**Describe the bug**
DriverListener [pool-35-thread-1-34] [ERROR] [Huawei_P] java.lang.IllegalArgumentException: Illegal base64 character 2e
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/carina/commit/20b015afb28533d3913db6d37a99dc87c8fee746

**Comment by okamara** [comment]
@vdelendik could you please add details or steps for verification this ticket
