### ISSUE TITLE
upgrade apache commons-text dependency 1.7->1.8

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1048]
to be in sync with zebrunner agents (zafira client) we have to bump up apache commons-text dependency to .8

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/carina/commit/1e543c2708008981284df36bb773b928bcf8a04e
6.4.37-SNAPSHOT+

**Comment by okamara** [comment]
@vdelendik could you please add details for testing this ticket?

**Comment by okamara** [comment]
Opened pom.xml and see that  <java.version>1.8</java.version>. Is it expected for this fix?

**Comment by okamara** [comment]
Tested via https://github.com/qaprosoft/carina/blob/196a41f07e34fda74adbaf48934e9ecad7e90ddc/pom.xml#L52
