### ISSUE TITLE
add L10N support for java 9+

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1050]
in scope of [#910 ](https://github.com/qaprosoft/carina/issues/910) we just fixed error messaging.
in this ticket we have to make L10N feature workable for java 11+.
11 because we suppose to jump to this version for carina

**Comment by FCosta20** [comment]
Please run location sample job "Web-Localization-Demo-Test" using 6.4.1031-SNAPSHOT carina build
https://github.com/qaprosoft/carina/pull/1154

**Comment by vdelendik** [comment]
closing per above comment. Let's test and merge if everything is ok. in scope of regression all api and web regressions should be executed on zebruner ce (branch develop). You can ask me howto update carina core version for all jobs easily

**Comment by vdelendik** [comment]
verified on CI using java 8 and 11.
