### ISSUE TITLE
Stackoverflow while trying to read configuration

### ISSUE THREAD

**Issue by ltpquang** [qaprosoft/carina#1052]
**Describe the bug**
When the configuration doesn't specify key `project_report_directory`, Carina will try to print warning, and also try to write to report file. To get the file path, it she then tries to read the key `project_report_directory`, causing infinity loop.

**Logs/Links**

The debugger can show clearer state

![image](https://user-images.githubusercontent.com/4617357/84491166-51923c00-acce-11ea-8037-e54afa6824d1.png)

![image](https://user-images.githubusercontent.com/4617357/84491253-72f32800-acce-11ea-8712-869181a87cfd.png)

**Mobile (please complete the following information):**
 - Device: emulator
 - OS: Android
 - Appium version: 1.17.1

**Additional context**

It happens only when I set `surefire`'s `forkCount` to 0. Set it to 1 causes no problem.

![image](https://user-images.githubusercontent.com/4617357/84492371-4a6c2d80-acd0-11ea-8006-ccf192bb3ee6.png)

In both case, the `_config.properties` still presents in `target` with valid configs.

** Update:

It seems that in 0 forkCount mode, R.CONFIG doesn't load override resource from `_config.properties`, since `ClassLoader.getSystemResource("_config.properties")` return `null`

Ref: https://maven.apache.org/surefire/maven-surefire-plugin/examples/class-loading.html

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/carina/pull/1102
6.4.40-SNAPSHOT

**Comment by vdelendik** [comment]
confirmed from xustomer that everything is ok
