### ISSUE TITLE
Incorrect Full TestNG HTML Report results

### ISSUE THREAD

**Issue by mmashkovich** [qaprosoft/carina#1062]
**Describe the bug**
Full TestNG HTML Report doesn't include all tests. For example, suite consists of 70 tests (and they are performed in info), but in results there are only 3.

**Comment by vdelendik** [comment]
that's a common TestNG functionality to "collapse" result for the same test into the single result. Usually happen with dataprovider tests where any pass test means +1 positive inside TestNG report. That's why we enhanced it inside carina/zafira reports
