### ISSUE TITLE
Getting warning for every step for cucumber runner.

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina#1063]
Carina Release: 6.4.37

Warning : 
Jun 25, 2020 11:17:18 AM io.cucumber.core.runtime.FeaturePathFeatureSupplier get
WARNING: No features found at classpath:/com/spdji

Runner details 
import com.qaprosoft.carina.core.foundation.cucumber.CucumberBaseTest;
import io.cucumber.testng.CucumberOptions;

@CucumberOptions(features = "src/test/resources/features/test1.feature",
        glue = "com.test",

        plugin = {"pretty",
                "html:target/cucumber-core-test-report",
                "pretty:target/cucumber-core-test-report.txt",
                "json:target/cucumber-core-test-report.json",
                "junit:target/cucumber-core-test-report.xml"}
        , monochrome = true
)
public class RunCucumberTest extends CucumberBaseTest {
}

Please let me know any more information is needed

**Comment by SergeiZagriychuk** [comment]
@prasadjshimpi to escape that warning make sure not to extend CucumberRunner class by your Steps classes.
if you need driver instance there simply add "implements IDriverPool" for your Step class.
Let me know if that resolves such warnings for you.

**Comment by vdelendik** [comment]
closing as of inactivity... @prasadjshimpi, please take a look to above comment
