### ISSUE TITLE
Cover PageOpeningStrategy feature in documentation and carina-demo

### ISSUE THREAD

**Issue by SergeiZagriychuk** [qaprosoft/carina#1074]
Need to:
- Add example of usage in carina-demo project
- update carina-archetype accordingly
- document it in carina official documentation

**Comment by DimaGrinevich** [comment]
https://github.com/qaprosoft/carina-demo/pull/150

**Comment by DimaGrinevich** [comment]
Need to check for language mistakes and text format

**Comment by okamara** [comment]
Verified for text format and language mistakes.
