### ISSUE TITLE
Priority is not working

### ISSUE THREAD

**Issue by Saleena21** [qaprosoft/carina#1075]
**Describe the bug**
Even though the Priority is set for test cases as below, its considering test case name ascending order for execution
@Test(priority=0)

**Web (please complete the following information):**
 - Chrome (83.0.4103.116)

**Additional context**
Was working previously

**Comment by vdelendik** [comment]
closed as TestNG vendor issue: https://github.com/cbeust/testng/issues/2170
we can't fix TestNG
