### ISSUE TITLE
Carina report: Link to test case is wrong

### ISSUE THREAD

**Issue by okamara** [qaprosoft/carina#1081]
Tested: jenkins-master: 5.1-beta1,qps-infra- develop, pipeline- develop
Steps:

Run Web demo tests
Open Carina report
Click on link to test AUTO-0008
Actual result: http://00.000.00.000/jenkins/job/okamara/job/carina-demo/job/Web-Demo-Test/1/CarinaReport/emailable-report.html#
Expected: Page for AUTO-0008 is opened

**Comment by vdelendik** [comment]
emailable report shouldn't contain href links if no jira integration url provided as command line args

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/carina/pull/1103
6.4.40-SNAPSHOT

by default after executing api or web carina-demo test "DEMO-0001" etc tasks in CarinaReport should be shown as regular text without urls!
to test links generation approach you can temporary add in hidden overrideFields such property
jira_url=https://mycopany.atlassian.net
As result in CarinaReport DEMO-0001 etc should be shown as links to https://mycopany.atlassian.net/**browse**/DEMO-0001

**Comment by dhreben** [comment]
Fixed.
