### ISSUE TITLE
headless tests should be started/executed using single property

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1082]
To run tests in headless mode we have to define required browsers args/preferneces. It would be greate to unify this process having dedicated headless_mode property (actual naming is TBD)

**Comment by dprymudrau** [comment]
fixed: #1107
6.4.41-SNAPSHOT

Test scenario:
Using overrideFields provide required headless=true value and 6.4.41-SNAPSHOT carina.
Execute web tests
Chrome and Firefox should start in headless mode
IE, Edge, Opera start with ui and 'Headless mode isn't supported by ${current_browser} browser' .

**Comment by okamara** [comment]
Tested. No messages about browsers in job logs.
