### ISSUE TITLE
[Mobile] ExtendedWebElement's check() and uncheck() methods don't work

### ISSUE THREAD

**Issue by ltpquang** [qaprosoft/carina#1084]
**Describe the bug**

The methods `isChecked()` works, it returns correct checking status of the checkbox. But `check()` and `uncheck()` do nothing.

**Logs/Links**

If applicable, attach console logs to help explain your problem.
Note: make sure you don't attach any private content like credentials etc in logs.  

**Mobile (please complete the following information):**
 - OS: Android
 - Appium version 1.17.1

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/carina/pull/1085
fix can be tested using 6.4.39-SNAPSHOT core build

**Comment by vdelendik** [comment]
tested on mine own
