### ISSUE TITLE
CarinaReport: be able to add logs/demo links inside internal emailable report to Zafira

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1086]
For now we support 2 emailable-report.html generation.
first one is independent CarinaReport which produce links to logs/screenshots saved locally. 2nd one is Zafira report which shows the same data but with a links to the external storages (S3, mino, ftp etc).

For default CI process we publish both reports CarinaReport and ZafiraReport to be able to compare in case of any infrastructure issue. As result some of the artifacts on CI occupies several Gb per build. 

So the goal of the feature:
Continue to deliver CarinaReport as is but organize an improvements to register external links to logs/demo onto the Zafira and don't publish those artifacts on CI.

Only if integration with Zafira is unavailable/corrupted we have to produce local links and publish all artifacts to CI

**Comment by vdelendik** [comment]
closing as won't fix. we don't publish local carina report onto CI anymore.

**Comment by dhreben** [comment]
Won't fix.Closed
