### ISSUE TITLE
Hub on huge load produce: Unable to determine type from: <. Last 1 characters read: <

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1089]
Selenium hub under load return too often empty response and WebDriverException:
`Unable to determine type from: <. Last 1 characters read: <`

Carina on the low level of finding element did only 2 attempts to find element and if both failed we had an exception in regular web/mobile tests.

ExtendedWebElement refindMethod should implement fluent waiter with RETRY_INTERVAL in ms as polling interval, EXPLICIT_TIMEOUT as an exception.

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/carina/pull/1090
6.4.40-SNAPSHOT+

**Comment by okamara** [comment]
Done. Closing based on customer feedback.
