### ISSUE TITLE
thumbnail images are not generated anymore by carina

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1097]
thumbnail generation for each screenshot moved onto the server part of zebrunner.
we have to fix local html report. default image icon can be used for all reports instead

**Comment by vdelendik** [comment]
issue fixed: https://github.com/qaprosoft/carina/pull/1101

**Comment by okamara** [comment]
Verified on carina-core_version=6.4.40-SNAPSHOT. Fixed.
