### ISSUE TITLE
Error: refindElement: searchContext is null for By.id: [id] (By.id: [id])

### ISSUE THREAD

**Issue by FredVaugeois** [qaprosoft/carina#1098]
For some reason, it seems as if the framework thinks that it is an error to use the findElement method when you have no search context (no parent element to execute the search) and logs an error whenever you do so. I agree that it could be considered a weak warning, but considering this as an error is, in my opinion, a bit too much.

We can clearly see in this code that it does not cause any error: it just uses driver.find instead of element.find whenever you have no search context, which is not an invalid behavior: 

![image](https://user-images.githubusercontent.com/26579806/91854334-970d3800-ec31-11ea-9087-95b09fe09db8.png)

Here is an example of what it looks like:

![image](https://user-images.githubusercontent.com/26579806/91854384-a9877180-ec31-11ea-990f-e3936c4f8513.png)

For this simple code: 

![image](https://user-images.githubusercontent.com/26579806/91854590-f2d7c100-ec31-11ea-8ac1-c644704cd5b3.png)

**Comment by vdelendik** [comment]
fixed in scope of #1089 ticket. 
https://github.com/qaprosoft/carina/pull/1090
6.4.40-SNAPSHOT

**Comment by okamara** [comment]
Can't verify this ticket.
