### ISSUE TITLE
Add the ability to encrypt data for the API request/response

### ISSUE THREAD

**Issue by FredVaugeois** [qaprosoft/carina#1130]
Hi!

This feature request is to basically have the ability to hide sensitive information in the logs of our API or database queries to make sure that this data is not visible for everyone. Right now, for the API, the authentication data is stored in the body of the requests and we often have to use identity token (as well as refresh tokens) which is extremely sensitive data and there is no way to currently hide this data in our logs.

So there are a few solutions that we could have, the best one being to have the same kind of behavior as we have in the driver crypto support (put ****** instead of the actual data), but we will also need to be able to tell the framework that a given API response needs to be hidden as well (whenever we request a refresh token for example). A temporary fix would be to allow us to dynamically disable logging when doing certain API/Database calls to make sure no information is logged.

Either way, I think a lot of solutions can solve this problem and any solution will be valuable to us!

**Comment by vdelendik** [comment]
updated subject to keep concrete request/response api feature request. It seems like new freemarker key neededlike sensitive or similar and extra logic to parse and replace such keys by ***.
Also submitted #1315 to publish in documentation steps we should use to reuse cryptotool for api, testdata and database config files
