### ISSUE TITLE
Annotation @CaseInsensitiveXPath doesn't work properly with xpath that contains syntax like '$1'

### ISSUE THREAD

**Issue by atataranovich** [qaprosoft/carina#1147]
**PRECONDITION:** 
element having xpath "//div[contains(@class, 't-product-unavailable')]/a/div[text()='Comprar %s']"

**STEPS:** 
1) add @CaseInsensitiveXPath an annotation to element
2) format it with using the string 'Presentes até R$169,90' 

**EXPECTED result:**
searching element by following value: '//div[contains(@class, 't-product-unavailable')]/a/div[translate(text(), 'COMPRAR PRESENTES ATÉ Rtext()='Comprar Presentes até R$169,90', 'comprar presentes até rtext()='Comprar Presentes até R$169,90')=translate('Comprar Presentes até Rtext()='Comprar Presentes até R$169,90', 'COMPRAR PRESENTES ATÉ Rtext()='Comprar Presentes até R$169,90', 'comprar presentes até rtext()='Comprar Presentes até R$169,90')]'

**ACTUAL result:**
searching element by following value: '//div[contains(@class, 't-product-unavailable')]/a/div[translate(text(), 'COMPRAR PRESENTES ATÉ Rtext()='Comprar Presentes até **R$169,90']69,90',** 'comprar presentes até rtext()='Comprar Presentes até **R$169,90']69,90'**)=translate('Comprar Presentes até Rtext()='Comprar Presentes até **R$169,90']69,90**', 'COMPRAR PRESENTES ATÉ Rtext()='Comprar Presentes até R$169,90']69,90', 'comprar presentes até rtext()='Comprar Presentes até **R$169,90']69,90**')]'
_**And as a result element is not found!**_

**Comment by DenisPitsul2020** [comment]
Could you check the expected result? It could be wrong. The problem might not be only in the end part - **']69,90**

Here is the part of the comment which describe the xpath translation in [toCaseInsensitive](https://github.com/qaprosoft/carina/blob/eda8e45d2e609bc5d66aa63b8e9cd5016b77fa9f/carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/locator/ExtendedElementLocator.java#L166) method: 

**Possible correct expected result:**
//div[contains(@Class, 't-product-unavailable')]/a/div[translate(text(), 'COMPRAR PRESENTES ATÉ R$169,90', 'comprar presentes até r$169,90')=translate('Comprar Presentes até R$169,90', 'COMPRAR PRESENTES ATÉ R$169,90', 'comprar presentes até r$169,90')]

**Comment by deNatallia** [comment]
Yep, you are right.

**Comment by atataranovich** [comment]
Yep, you are right.

**Comment by vdelendik** [comment]
fix merged:
https://github.com/qaprosoft/carina/pull/1268

**Comment by okamara** [comment]
too complicated to repro and verify this ticket.
