### ISSUE TITLE
capabilities.ADB_ENABLED needed for android appium tests

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1161]
for now we automatically connect via adb to android device when STF_ENABLED is true. we have to split these settings and provide possibility to use STF integration to occupy device and don't connect to ADB.
So let's update connect and disconnect method for Device object. Only when explicit Capabilities.ADB_ENABLED is provided we have to connect/disconnect.

P.S. Also as it is 7.0 feature let's think about renaming to capabilities.enableStf and capabilities.enableAdb as we have for video, logs etc

**Comment by vdelendik** [comment]
done. details can be found in the ticket about STF_ENABLED removal: #1209

**Comment by okamara** [comment]
Verified on customer. Fixed.
