### ISSUE TITLE
ugly IllegalArgumentException for L10N on jdk8

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1163]
21:50:44  2020-11-04 18:50:43 CarinaListener [main-1] [ERROR] L10N bundle is not initialized successfully!
21:50:44  java.lang.IllegalArgumentException: URI is not hierarchical
21:50:44  	at java.io.File.<init>(File.java:418)
21:50:44  	at com.qaprosoft.carina.core.foundation.utils.resources.Resources.getResourceURLs(Resources.java:80)
21:50:44  	at com.qaprosoft.carina.core.foundation.utils.resources.L10N.init(L10N.java:59)
21:50:44  	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.<clinit>(CarinaListener.java:127)
21:50:44  	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
21:50:44  	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
21:50:44  	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
21:50:44  	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
21:50:44  	at java.lang.Class.newInstance(Class.java:442)
21:50:44  	at com.nordstrom.automation.testng.ListenerChain.attachListener(ListenerChain.java:676)
21:50:44  	at com.nordstrom.automation.testng.ListenerChain.processLinkedListeners(ListenerChain.java:639)
21:50:44  	at com.nordstrom.automation.testng.ListenerChain.attachListeners(ListenerChain.java:610)
21:50:44  	at com.nordstrom.automation.testng.ListenerChain.transform(ListenerChain.java:83)
21:50:44  	at org.testng.internal.annotations.JDK15AnnotationFinder.transform(JDK15AnnotationFinder.java:168)
21:50:44  	at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:239)
21:50:44  	at org.testng.internal.annotations.JDK15AnnotationFinder.findAnnotation(JDK15AnnotationFinder.java:109)
21:50:44  	at org.testng.internal.TestNGClassFinder.isTestNGClass(TestNGClassFinder.java:280)
21:50:44  	at org.testng.internal.TestNGClassFinder.isNotTestNGClass(TestNGClassFinder.java:265)
21:50:44  	at org.testng.internal.TestNGClassFinder.processClass(TestNGClassFinder.java:98)
21:50:44  	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:71)
21:50:44  	at org.testng.TestRunner.initMethods(TestRunner.java:439)
21:50:44  	at org.testng.TestRunner.init(TestRunner.java:338)
21:50:44  	at org.testng.TestRunner.init(TestRunner.java:291)
21:50:44  	at org.testng.TestRunner.<init>(TestRunner.java:179)
21:50:44  	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:613)
21:50:44  	at org.testng.SuiteRunner.init(SuiteRunner.java:178)
21:50:44  	at org.testng.SuiteRunner.<init>(SuiteRunner.java:112)
21:50:44  	at org.testng.TestNG.createSuiteRunner(TestNG.java:1275)
21:50:44  	at org.testng.TestNG.createSuiteRunners(TestNG.java:1251)
21:50:44  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1100)
21:50:44  	at org.testng.TestNG.runSuites(TestNG.java:1039)
21:50:44  	at org.testng.TestNG.run(TestNG.java:1007)
21:50:44  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
21:50:44  	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
21:50:44  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
21:50:44  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
21:50:44  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
21:50:44  	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
21:50:44  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)

**Comment by DenisPitsul2020** [comment]
Can't reproduce. 
Run web-localization test from carina-demo project with jdk1.8
Attached text file with logs of test. 
[Uploading TestRunLogs.txt…]()

**Comment by DenisPitsul2020** [comment]
Can't reproduce.
Run web-localization test from carina-demo project with jdk1.8
Attached text file with logs of test.
[https://drive.google.com/file/d/1-HrTuMoovrpR9gOXlIvZLycWQC7qSOHC/view?usp=sharing](TestRunLogs)

**Comment by DenisPitsul2020** [comment]
Can't reproduce.
Run web-localization test from carina-demo project with jdk1.8
Attached text file with logs of test.
[https://drive.google.com/file/d/1-HrTuMoovrpR9gOXlIvZLycWQC7qSOHC/view?usp=sharing](url)

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/carina/commit/b4670080965cfd33b1db682a6a35cc666bcefe55
root cause - missed L10N folder among resources

**Comment by okamara** [comment]
Verified, folder is present.
