### ISSUE TITLE
remove alice-ai client from carina 

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1164]
alice-ai is still too expensive to use it in web/mobile automation. Also declared client is too old with rather out-of-dates dependencies we have in classpath. Let's remove it and all related code

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/carina/commit/e375b98a67ed254ce51e1e577e471a315d753537

**Comment by dhreben** [comment]
Verified. Alice-ai client is removed from carina.
