### ISSUE TITLE
Upgrade Logging library

### ISSUE THREAD

**Issue by ltpquang** [qaprosoft/carina#1168]
Carina is now using log4j 1.2.17 for logging, which is end of life as of [Aug 5, 2015](https://logging.apache.org/log4j/1.2/manual.html)

Should we go for an upgrade?

**Comment by vdelendik** [comment]
we know that log4j 1 is deprecated and not supported but: https://logging.apache.org/log4j/log4j-2.2/manual/migration.html

```
Using the Log4j 1.x bridge
Perhaps the simplest way to convert to using Log4j 2 is to replace the log4j 1.x jar file with Log4j 2's log4j-1.2-api.jar. However, to use this successfully applications must meet the following requirements:

They must not access methods and classes internal to the Log4j 1.x implementation such as Appenders, LoggerRepository or Category's callAppenders method.
They must not programmatically configure Log4j.
They must not configure by calling the classes DOMConfigurator or PropertyConfigurator.
```

in carina we all all three features which make movement not so easy. Globally in 7.0 for carina-archetype we exclude log4j 1.2.17 dependency and configure valid slf4j cascade with example. So on test project level you could reuse any preferable logger from the list: log4j, log4j2 or logback.

approach will e described after release but in general it should be something like: https://github.com/zebrunner/java-agent-testng#collecting-test-logs
