### ISSUE TITLE
minimize test configuration logging in the beginning of the test

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1173]
As you can see below we have around 100 lines with default test configuration arguments.
Just removing from logging those which value is null could minimize those lines to 60.

Also think about the "optional/required" boolean flag for each option in Configuration.java and don't display optional args which value is default.
Example of the obligatory default argument:
env=DEMO
max_driver_count=3
max_screen_history=0
max_log_file_size=150
```
Example of the optional argument which has default value and might be omited:
```
proxy_protocols=http,https,ftp
browsermob_proxy=false
browsermob_port=0
date_format=HH:mm:ss yyyy-MM-dd
time_format=HH:mm:ss
```


Overall log message:
```
============= Test configuration =============
url=https://www.gsmarena.com
env=DEMO
env_arg_resolver=com.qaprosoft.carina.core.foundation.utils.DefaultEnvArgResolver
browser=chrome
browser_version=
browser_language=
selenium_host=...
driver_event_listeners=
max_driver_count=3
custom_capabilities=
chrome_args=
chrome_experimental_opts=
chrome_mobile_emulation_opts=
firefox_args=
firefox_preferences=
headless=false
app_version=
proxy_host=
proxy_port=
proxy_protocols=http,https,ftp
no_proxy=
browsermob_proxy=false
browsermob_host=
browsermob_port=0
browsermob_ports_range=
browsermob_disabled_mitm=false
proxy_set_to_system=false
report_url=
track_known_issues=false
auto_screenshot=true
explicit_timeout=20
auto_download=false
auto_download_apps=
auto_download_folder=
custom_artifacts_folder=
retry_interval=5
project_report_directory=./reports/qa
max_screen_history=0
max_log_file_size=150
result_sorting=true
big_screen_width=-1
big_screen_height=-1
init_retry_count=0
init_retry_interval=1
retry_count=0
enable_l10n=true
l10n_encoding=ISO-8859-1
locale=en_US
thread_count=1
data_provider_thread_count=1
core_log_level=INFO
core_log_packages=com.qaprosoft.carina.core
artifacts_expiration_seconds=2592000
log_all_json=true
date_format=HH:mm:ss yyyy-MM-dd
time_format=HH:mm:ss
suite_name=
jira_url=
test_naming_pattern={method_name}
element_loading_strategy=BY_PRESENCE_OR_VISIBILITY
page_opening_strategy=BY_URL_AND_ELEMENT
forcibly_disable_driver_quit=false
s3_bucket_name=
access_key_id=
secret_key=
s3_use_presign_url=false
s3_local_storage=.
appcenter_token=
appcenter_local_storage=.
add_new_localization=false
add_new_localization_encoding=utf-8
add_new_localization_path=
add_new_localization_property_name=new_custom_messages_
tls_keysecure_location=
health_check_class=
health_check_methods=
uninstall_related_apps=false
default_device_timezone=GMT
default_device_time_format=24
default_device_language=en_US
android_screen_record_size=
android_screen_record_bitrate=1000000
android_enable_bug_report=true
ios_screen_record_quality=MEDIUM
ios_screen_record_codec=libx264
ios_screen_record_fps=10
screen_record_duration=180
video_scale=-2:720
ignore_ssl=false
test_run_rules=
selenium_host=...

------------- Driver capabilities -----------
================================================
```

**Comment by DenisPitsul2020** [comment]
Removing from logging parameters from test configuration which value is null.
#1194

**Comment by DenisPitsul2020** [comment]
#1194 
Removing logging parameters from test configuration which value is null.

**Comment by vdelendik** [comment]
done
