### ISSUE TITLE
remove custom logs/video download after driver quit

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1174]
we should review `IDriverPool->quitDriver(CarinaDriver carinaDriver, boolean keepProxyDuring)` method.
for embedded zebrunner selenoid and appium sessions independent uploader to s3 should happen. So there is no need to do extra calls on quit operation as it potentially produce a lot of similar issues:
`org.openqa.selenium.json.JsonException: Unable to determine type from: H. Last 1 characters read: H`

in upcoming 6.5 release we are trying to handle it by repeiting the selenium/appium call via EventFiringAppiumCommandExecutor/EventFiringSeleniumCommandExecutor overriding

**Comment by vdelendik** [comment]
closing as video related improvements established:
1. `mobile_screen_record_enable` property added which can start/stop video recording and upload to local `./qa/reports` location
2. this property if `false` by default as new zebrunner device farm hub should be able to do it on their own
3. For those who run on their local appium servers they could enable this feature and make video recording but only for local reporting usage
4. #1206 enhancement submitted to integrate video links to embedded CarinaReport
5. renaming this ticket to video related only and closing
6. new ticket to review appium logs should be submitted soon

**Comment by okamara** [comment]
Verified on customer. Fixed.
