### ISSUE TITLE
Disable DriverListener analysis for capturing screenshot method

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1177]
Capture screenshot method handle all kind of exce[tion on their own. Moreover, that's the most risky operation right after the failure because a lot of issues occur when driver corrupted/died/not accessible.
For now we have a lot of login in DriverListener to avoid recursive cycles during screenshots generation failure. As a global fix it is recommended to castDriver removing default listener at all before making an attempt to do a screenshot and capture failures only in Screenshot.java clas

**Comment by okamara** [comment]
Verified on client's app.
