### ISSUE TITLE
take a decisoin about jacoco plugin usage

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1179]
earlier it was used to generate valuable statistic of used classes/lines. Using those information we already refactored tons of code and disabled it's usage on CI/CD.
If desicion is to rmove this plugin from carina we have to submit the same tickets for these repositories as well:
carina and carina-archetype submodule
carina-demo
pipeline-ce 

and also inform users that it might be removed in their pom.xml files

**Comment by vdelendik** [comment]
we are going to remove it completely as we don't use it so far. It's role to show unit testing coverage was very helpful between 5 and 6th core generation

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/carina/commit/b1c1275c44ac8023734f2240dbedb92081583f90

**Comment by okamara** [comment]
Verified on customer. Fixed.
