### ISSUE TITLE
don't raise exception for opera/ie/edge/safari if english locales provided

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1180]
Unable to execute default web sample tests in carina archetype for opera because of added default "locale=en_US"
Let's exemine OperaCapabilities (ie, edge and safari) to avoid an exception if en or en_US locale is provided.
So final code should like like
```
        if (!browserLang.isEmpty() && !browserLang.contains("en_US") {
        	Assert.fail("Unable to change Opera locale via selenium! (" + browserLang + ")");
        }
```

log file: 
18:25:40  2020-11-08 15:25:40 Messager [TestNG-test=GSM arena web tests-1-18] [INFO]  TEST [GSM arena web tests - testNewsSearch] STARTED at [15:25:40 2020-11-08]
18:25:40  2020-11-08 15:25:40 Messager [TestNG-test=GSM arena web tests-1-18] [ERROR]  TEST [GSM arena web tests - testNewsSearch] FAILED at [15:25:40 2020-11-08] - Unable to change Opera locale via selenium! (en_US)
18:25:40  
18:25:40  org.testng.Assert.fail(Assert.java:97)
18:25:40  com.qaprosoft.carina.core.foundation.webdriver.core.capability.impl.desktop.OperaCapabilities.getCapability(OperaCapabilities.java:37)
18:25:40  com.qaprosoft.carina.core.foundation.webdriver.core.factory.impl.DesktopFactory.getCapabilities(DesktopFactory.java:150)
18:25:40  com.qaprosoft.carina.core.foundation.webdriver.core.factory.impl.DesktopFactory.create(DesktopFactory.java:63)
18:25:40  com.qaprosoft.carina.core.foundation.webdriver.core.factory.DriverFactory.create(DriverFactory.java:73)
18:25:40  com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.createDriver(IDriverPool.java:511)
18:25:40  com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:161)
18:25:40  com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:96)
18:25:40  com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:84)
18:25:40  com.qaprosoft.carina.demo.WebSampleTest.testNewsSearch(WebSampleTest.java:99)
18:25:40  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:25:40  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:25:40  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:25:40  java.base/java.lang.reflect.Method.invoke(Method.java:566)
18:25:40  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
18:25:40  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
18:25:40  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
18:25:40  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
18:25:40  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
18:25:40  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
18:25:40  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
18:25:40  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
18:25:40  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
18:25:40  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
18:25:40  java.base/java.lang.Thread.run(Thread.java:834)

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/carina/pull/1198
as a test scenario we should run vs opera, ie and edge using non default browser_language... let's say fr and ja

**Comment by okamara** [comment]
I see error messages if run web_demo test via Jenkins for ie with browser_language=de_DE:
14:56:47  2020-11-25 11:56:47 Messager [TestNG-test=GSM arena web tests-1-1] [INFO]  TEST [GSM arena web tests - testCompareModels] STARTED at [11:56:47 2020-11-25]
14:56:47  2020-11-25 11:56:47 IDriverPool [TestNG-test=GSM arena web tests-1-20] [ERROR] Driver initialization 'default' FAILED! Retry 1 of 1 time - Unsupported browser: ie, browser_language
14:56:47  java.lang.RuntimeException: Unsupported browser: ie, browser_language
14:56:47  	at

**Comment by okamara** [comment]
Verified with opera browser
1. In configure for web_demo test set: override field as carina-core_version=6.5.46, browser_language=de_DE
2. In Web_demo test set browser=opera
3. Verify that job completed in jenkins without errors and in reporting video session in browser language is DE
Actual result:job completed in jenkins without errors but in reporting video session in browser language hard to see it is ENG or DE
