### ISSUE TITLE
Screenshots are not getting saved on local machine

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina#1200]
[
![photo_2020-11-17_18-25-18](https://user-images.githubusercontent.com/31615407/99392839-5fde2700-2902-11eb-9c42-6d9a8f1838b6.jpg)
](url)

Please refer the attached image 

With the below versions, screenshot are only getting captured at the failures (earlier I can see all the screenshots for actions)
is any property introduced which I missed?
carina-core: 7.0.0-beta1
carina-cucumber: 1.2-beta1

I already set auto_screenshot=true

**Comment by szagriychuk-ua** [comment]
I tested carina-core: 7.0.0-beta1 in regular web test and found that screenshots are missing there as well.
At the same time same test works well with latest 6th carina 6.5.45 (in terms of screenshots)
So the problem is definitely in carina-core modules and not related to cucumber.
cc @vdelendik

**Comment by vdelendik** [comment]
fixed.
testing can be done using:
carina-core: 7.0.0-beta2-SNAPSHOT
carina-cucumber: 1.2-beta2-SNAPSHOT

**Comment by okamara** [comment]
Verified. Fixed.
