### ISSUE TITLE
Add ability to generate carina-based project from archetype without carina-demo sources

### ISSUE THREAD

**Issue by SergeiZagriychuk** [qaprosoft/carina#1204]
Right now by default project generated from archetype has carina-demo sources as sample of different types of tests.
But in some cases those classes are not needed and just empty project with packages structure and all the dependencies is required.
It would be nice to add such option into building from archetype process.

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/carina/pull/1207
