### ISSUE TITLE
provide link to mobile video recording inside default emailable report

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1206]
We continue to manage mobile video recordings for non zebrunner hubs by default. 
```
driver_recorder=true
```
As result some video files can be generated as artifacts. As we don't plan to publish CarinaReport to jenkins we can add Video link as part of local emailable report.

**Comment by vdelendik** [comment]
investigate possibility to enhance image gallery to incorporate embedded player if video file(s) exist

**Comment by vdelendik** [comment]
7.0.2-SNAPSHOT

**Comment by okamara** [comment]
too complicated to repro and verify
