### ISSUE TITLE
redesign communication with grid removing RemoteDevice from common models

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1208]
RemoteDevice was implemented for transferring STF device metadata via grid servlet. In 4th generation of carina we replaced this approach using slotCapabilities object.
So we have to remove this class and reorganize MobileFactory code accordingly

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/carina/pull/1210

no more RemoteDevice class at all. All communication with any selenium hub is organized via capabilities.
For zebrunner device farm (MCloud) we also use extra slotCapabilities sub-component to share xtra information.

Testing might be performed over old selenium-hub and upcoming new mcloud-grid as well.
7.0.0-beta3-SNAPSHOT

**Comment by okamara** [comment]
Verified as it is working now. Fixed.
