### ISSUE TITLE
replace STF_ENABLED by enableAdb capability

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1209]
stf integration is hub <-> stf related server argument which can't be controlled by carina.
historically this attribute was used to define adb connection strategy. 
in 7.0 we suppose to rename it to make clearer

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/carina/pull/1210

adb integration is disabled by default. to make it available we have to provide explicitly
capabilities.enableAdb=true

We could try to do `adb connect` only if remoteUrl is available from STF or device udid available for local connect.
Also as a requirement for local run `adb` should be available in the PATH for Eclipe or Idea

**Comment by okamara** [comment]
Verified on customer. Fixed.
