### ISSUE TITLE
remove custom logs download after driver quit

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1211]
#1174 has all details. 
Need review driver logs download/upload. Ideally keep this functionality only for local runs and move to backend for selenoid and mcloud-grid

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/carina/commit/f63f3d6db0ecfecd80b6556a739e65d56b85bd93

**Comment by okamara** [comment]
Verified by Vadim. Fixed.
