### ISSUE TITLE
Add support for setting intl.accept_languages as part of capabilities in Chrome BROWSER_LANGUAGE support

### ISSUE THREAD

**Issue by dkline-920** [qaprosoft/carina#1225]
**Describe the solution you'd like**
In AbstractCapabilities, under FireFox, if browser_language is set in the _config.properties, then the intl.accept_languages is set in the profile, but the same is not true for Chrome.  In the code for addChromeOptions, would like to see the hashmap added to the options as well as the --lang argument that is already added.

Something like:
        Map<String, Object> prefs = new HashMap<>();
        prefs.put("intl.accept_languages", "en");
        options.setExperimentalOption("prefs", browserlang);

of course, there is already code that sets prefs in options if AUTO_DOWNLOAD is set and can't add prefs twice, so have to handle the case where both occurs.  I think create the Map before checking the language and download and then do the puts in the respective checks and then at the end, do an OR of the 2 conditions to see if we need to add the prefs Map to options?

**Comment by vdelendik** [comment]
@dkline-920, changes can be tested in 7.0.0-SNAPSHOT.
due to the migrating to new infrastructure on Java11 building snapshot on PullRequest not available yet

**Comment by okamara** [comment]
Should be verified later next week.

**Comment by okamara** [comment]
Verified by community. Fixed.
