### ISSUE TITLE
Get system environment variables into the _config.properties file 

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [qaprosoft/carina#1227]
**Describe the solution you'd like**
Is there a way to get system environment variables into the config.properties file. An example where this could be useful is to automatically  get the user name of the person running the tests i.e `user=${env:whoami}` or get the current project path `location=${env:pwd}`

**Comment by vdelendik** [comment]
@Ashraf-Ali-aa we can't load all system env variables into the config as it might be security breach. At the same time I can suggest such variant:
1. we read from core config.properties and all _config.properties, __config.properties etc
**2. for every declared property from config files read env variable value and replace previous value if exists**
3. for every declared property from config files read java argument value and replace previous value if exists

Are you ok with added #2?

**Comment by Ashraf-Ali-aa** [comment]
@vdelendik thanks for the explanation, Just wanted to clarify if I sent an environment variable called USER=test and on the config file I set env=USER then I should be able to get access to the value in the config by using ${USER}

**Comment by Ashraf-Ali-aa** [comment]
is it possible to get the current working directory path in the config file?

**Comment by Ashraf-Ali-aa** [comment]
I have manged to figure out a way to set config properties by running the below method using `@BeforeSuite` annotation

```
private static void overrideConfigProperties() {
        R.CONFIG.put("base_path", System.getProperty("user.dir"));
    }
```
