### ISSUE TITLE
404 error after redirection to zebrunner.com

### ISSUE THREAD

**Issue by dhreben** [qaprosoft/carina#1229]
**Test scenario:**

1.Open (https://github.com/qaprosoft/carina/blob/master/README.md)
2.Tap Try it out for free.

**Actual result:**  404 error after redirection to zebrunner.com

<img width="1060" alt="Screenshot 2021-01-16 at 17 34 12" src="https://user-images.githubusercontent.com/50950954/104814794-b8a63f00-5821-11eb-9666-b45b8f16c5c9.png">

**Comment by vdelendik** [comment]
fixed on master. link will redirect just to zebrunner.com

**Comment by dhreben** [comment]
Fixed
