### ISSUE TITLE
publish har files to zebrunner reporting as artifact

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1235]
To simplify sharing of the har files artifacts we have to organize automatic file publishing to reporting if enabled.
Also we have to prohibit har files publishing as part of the pipeline.
Step seems valid for sharing any generated artifact (not only har file)

**Comment by vdelendik** [comment]
done. need to test using test code which generate har report

**Comment by okamara** [comment]
Verified on master.
No har files report 
<img width="611" alt="Screen Shot 2021-01-25 at 4 50 38 PM" src="https://user-images.githubusercontent.com/32964663/105714570-8f766480-5f2d-11eb-8c4b-8be9b565edbe.png">

**Comment by okamara** [comment]
Verified on master branch. Fixed.
