### ISSUE TITLE
declare default boolean config parameters as NULL (false)

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1236]
to minimize number of log messages in the beginning of the test it is recommended to declare all default boolean args as NULL in config.properties.
Also `Configuration.getBoolean(name)` should be adjusted to return false if NULL.

**Comment by vdelendik** [comment]
done. during the testing run api demo test using 7.0.0-SNAPSHOT carina core version.
Verify that in the beginning of the logs there are NOT such lines:
============= Test configuration =============
driver_recorder=false
headless=false
browsermob_proxy=false
browsermob_disabled_mitm=false
proxy_set_to_system=false
track_known_issues=false
auto_download=false
forcibly_disable_driver_quit=false
s3_use_presign_url=false
add_new_localization=false
uninstall_related_apps=false
ignore_ssl=false

**Comment by dhreben** [comment]
Verified.
