### ISSUE TITLE
Add Exception for not implemented methods

### ISSUE THREAD

**Issue by dzmitry-pinchuk** [qaprosoft/carina#1240]
**Describe the solution you'd like**
Add Exception for not implemented methods

**Additional context**
Example: we have the realization of abstract method only for one platform. I propose to create an exception that will generate the correct message with method name and platform mane. `Method [methodName] isn't implemented for [platformName]!`

**Comment by dzmitry-pinchuk** [comment]
https://github.com/qaprosoft/carina/pull/1241

**Comment by vdelendik** [comment]
merged. feature can be tested in 7.0.1-SNAPSHOT
