### ISSUE TITLE
document extended getDriver() usage with custom capabilitites

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1247]
we have to publish detailed information about advanced usage of the browser capabilities like below. Put thi sinfo into thw web automation section
```
1. init default capabilities:
DesiredCapabilitites caps = new ChromeCapabilities().getCapability(name);
2. add custom options
ChromeOptions options = new ChromeOptions();
options.setExperimentalOption(name, value);
...
3. put your options into the caps
caps.setCapability(ChromeOptions.CAPABILITY, options);
4. reuse extended getDriver method
getDriver(String name, DesiredCapabilities capabilities)
```

**Comment by DimaGrinevich** [comment]
Need to check for language mistakes and text format
http://qaprosoft.github.io/carina/advanced/driver/

**Comment by okamara** [comment]
@vdelendik could not find info about browser capabilities in http://qaprosoft.github.io/carina/automation/web/

**Comment by okamara** [comment]
Verified for language mistakes and text format
http://qaprosoft.github.io/carina/advanced/driver/
