### ISSUE TITLE
Numbers are shifted in  "Setting up cucumber test with carina"

### ISSUE THREAD

**Issue by okamara** [qaprosoft/carina#1248]
**Describe the bug**
1. Open http://qaprosoft.github.io/carina/cucumber/
2. Verify Text and placement for numbers
Actual result: Numbers are shifted in  "Setting up cucumber test with carina"

**Logs/Links**
http://qaprosoft.github.io/carina/cucumber/

<img width="701" alt="Screen Shot 2021-02-01 at 11 52 24 AM" src="https://user-images.githubusercontent.com/32964663/106457397-fc46ad00-649f-11eb-97a2-bf3b0fad031c.png">

**Comment by DimaGrinevich** [comment]
Text should be in the expected format

**Comment by okamara** [comment]
Verified. Done.
