### ISSUE TITLE
find valid way to reuse drivers started in BeforeTest

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1250]
TestNG supports @BeforeTest annotation which belong to `<test...>` tag in suite xml file.
For now drivers started in that place can't be detected by test code.

We should update logic and return driver by name from this phase as well

**Comment by okamara** [comment]
@DimaGrinevich what feature branch in carina-demo and where it is possible to test?

**Comment by okamara** [comment]
verified by @DimaGrinevich. Fixed.
