### ISSUE TITLE
Enhancement : Copy final emailable-report.html to our run-specific results folder

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina#1254]
Copy final emailable-report.html to our run-specific results folder

D:/Automation/QA_Automation/reports/emailable-report.html
to 
D:/Automation/QA_Automation/reports/**1613739999290/**

**Comment by DimaGrinevich** [comment]
pull: #https://github.com/qaprosoft/carina/pull/1262


1) open carina-demo
2) start any test

now final emailable-report.html will be at your project_report_directory folder (by default /reports)
and at specific test session folder (/reports/1614779340710)

**Comment by vdelendik** [comment]
tested successfully
