### ISSUE TITLE
Demo (Slides) link exists in emailable report even if no png screenshots generated by test

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1261]
I see in upcoming 7.0.2-SNAPSHOT core build that link onto the Slides available even for API tests which is wrong.
![image](https://user-images.githubusercontent.com/4551455/109708512-8d4a9a00-7bac-11eb-899b-1619c5665a90.png)

Let's inspect code and return old logic which verify preliminary presence of png files and maybe internal test html report before adding "Slides" link inside global report

**Comment by vdelendik** [comment]
fixed. changes can be tested using 7.0.3-SNAPSHOT carina

**Comment by okamara** [comment]
@DimaGrinevich could you please run web and api jobs and attach images to the ticket for verification.

**Comment by DimaGrinevich** [comment]
For web:
![Screenshot 2021-04-28 at 14 31 20](https://user-images.githubusercontent.com/78387779/116398648-b431ef00-a830-11eb-9aa8-b9e260fd1f98.png)
![Screenshot 2021-04-28 at 14 31 33](https://user-images.githubusercontent.com/78387779/116398656-b6944900-a830-11eb-94b9-0c24f7cc1a61.png)

**Comment by DimaGrinevich** [comment]
For api:
![Screenshot 2021-04-28 at 14 32 32](https://user-images.githubusercontent.com/78387779/116398696-c318a180-a830-11eb-8ac2-1771b31b4b25.png)
