### ISSUE TITLE
cant change the path to a folder where testing reports are saved

### ISSUE THREAD

**Issue by DimaGrinevich** [qaprosoft/carina#1263]
In carina-demo __config.properties i set parameter project_report_directory=./myReports 

expected:
report generates an new folder named myReports
actual:
report generates to the folder named reports

the same issue with parameter max_screen_history

for example: 
i set parameters 
project_report_directory=./myReports/android
max_screen_history=15

my test:
@Test
    public void testOneMore(){
        System.out.println(R.CONFIG.get("project_report_directory"));
        System.out.println(R.CONFIG.get("max_screen_history"));
    }

output: 
2021-03-03 11:26:59 Messager [main-1] [INFO]  TEST [carina - testOneMore] STARTED at [11:26:59 2021-03-03]
./reports
0
2021-03-03 11:26:59 Messager [main-1] [INFO]  TEST [carina - testOneMore] PASSED at [11:26:59 2021-03-03]

**Comment by DimaGrinevich** [comment]
now we can set a folder for test reports and max number of screenshot history.

by default, folder for reports: ./reports; number of screenshot history: 10


1) open carina-demo
2) enter __config.properties
3) set new folder for project_report_directory that starts with / (for example project_report_directory=/tmp/myreports)
4) set max_screen_history property with positive number (for example max_screen_history=2)
5) create new Test in src.test.java, for example:
public class TestAbs extends AbstractTest {
    @Test
    public void testOneMore() {
        System.out.println(“report directory: ” + R.CONFIG.get(“project_report_directory”));
        System.out.println(“max screen history: “+ R.CONFIG.get(“max_screen_history”));
    }
}
6) launch test

we expect:
1) created new folder with test reports (in our case it is /tmp/myreports)
2) console output match the expected (in our case it is :
	report directory: /tmp/myreports
	max screen history: 2
)


if we comment this parameters
#project_report_directory=/tmp/myreports
#max_screen_history=2
or leave an empty value
project_report_directory=
max_screen_history=
or set values as NULL
project_report_directory=NULL
max_screen_history=NULL
we expect default values to be set in project
./reports for project_report_directory
10 for max_screen_history

we can test it with the help of test above

**Comment by okamara** [comment]
@DimaGrinevich could you please check and close this ticket?
