### ISSUE TITLE
Can't initiate edge/opera/safari driver with getDriver(new AbstractCapabilities().getCapability())

### ISSUE THREAD

**Issue by DimaGrinevich** [qaprosoft/carina#1265]
I got a test:

    public void multipleBrowserTest() {
        HomePage chromeHomePage = new HomePage(getDriver("chrome", new ChromeCapabilities().getCapability("Chrome Test")));
        chromeHomePage.open();
        Assert.assertTrue(chromeHomePage.isPageOpened(), "Chrome home page is not opened!");

        HomePage firefoxHomePage = new HomePage(getDriver("firefox", new FirefoxCapabilities().getCapability("Firefox Test")));
        firefoxHomePage.open();
        Assert.assertTrue(firefoxHomePage.isPageOpened(), "Firefox home page is not opened!");

        HomePage safariHomePage = new HomePage(getDriver("safari", new SafariCapabilities().getCapability("Safari test")));
        safariHomePage.open();
        Assert.assertTrue(safariHomePage.isPageOpened(), "Safari home page is not opened!");

        HomePage edgeHomePage = new HomePage(getDriver("edge", new EdgeCapabilities().getCapability("Edge test")));
        edgeHomePage.open();
        Assert.assertTrue(edgeHomePage.isPageOpened(), "Edge home page is not opened!");

        HomePage operaHomePage = new HomePage(getDriver("opera", new OperaCapabilities().getCapability("Opera test")));
        operaHomePage.open();
        Assert.assertTrue(operaHomePage.isPageOpened(), "Opera home page is not opened!");
    }

When launching on pc i expect 5 different browsers to open

actually opens
for ChromeCapabilities = chrome
for FirefoxCapabilities = firefox
for SafariCapabilities = chrome, expected safari
for EdgeCapabilities = chrome, expected microsoft edge
for OperaCapabilities = chrome, expected opera

**Comment by DimaGrinevich** [comment]
1) download driver for every used browser
2) place it in the same folder as selenium-server
3) launch selenium in terminal: java -jar selenium-server-standalone-X.jar

4) create test in carina-demo
@Test
public void multipleBrowserTest() {
    HomePage chromeHomePage = new HomePage(getDriver("chrome", new ChromeCapabilities().getCapability("Chrome Test")));
    chromeHomePage.open();
    Assert.assertTrue(chromeHomePage.isPageOpened(), "Chrome home page is not opened!");

    HomePage firefoxHomePage = new HomePage(getDriver("firefox", new FirefoxCapabilities().getCapability("Firefox Test")));
    firefoxHomePage.open();
    Assert.assertTrue(firefoxHomePage.isPageOpened(), "Firefox home page is not opened!");

    HomePage safariHomePage = new HomePage(getDriver("safari", new SafariCapabilities().getCapability("Safari test")));
    safariHomePage.open();
    Assert.assertTrue(safariHomePage.isPageOpened(), "Safari home page is not opened!");

    HomePage edgeHomePage = new HomePage(getDriver("edge", new EdgeCapabilities().getCapability("Edge test")));
    edgeHomePage.open();
    Assert.assertTrue(edgeHomePage.isPageOpened(), "Edge home page is not opened!");

    HomePage operaHomePage = new HomePage(getDriver("opera", new OperaCapabilities().getCapability("Opera test")));
    operaHomePage.open();
    Assert.assertTrue(operaHomePage.isPageOpened(), "Opera home page is not opened!");
}

5) Run this test
6) browsers should opened in appropriate order:
    1) Chrome
    2) Firefox
    3) Safari
    4) Edge
    5) Opera

**Comment by okamara** [comment]
@DimaGrinevich could you please test and close this ticket.
