### ISSUE TITLE
review if we need enable_l10n property

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1273]
property was added to skip localization resources load/init to speed up it for default english runs.
it looks like using Java 11 it is not a problem anymore and we could load any resource super fast if exist.
So let's investigate and remove this argument if not needed

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/carina/pull/1288

**Comment by vdelendik** [comment]
7.0.3-SNAPSHOT

**Comment by okamara** [comment]
Verified on 7.0.3-SNAPSHOT. Fixed.
