### ISSUE TITLE
localization of list of extendedwebelement

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina#1277]
One more feature I would like to suggest you while doing localization. 
can we have localization of list of extendedwebelement.  It is not creating file as it is not able to find the keys 
sharing with you small code snippet 

    @FindBy(id = "user-login")
    private ExtendedWebElement userLogin;

    @FindBy(xpath = "//div[@class='hrd-primary-nav-links']/ul/li/a")
    private List<ExtendedWebElement> menuLinks;

        menuLinks.add(userLogin);
        ExtendedWebElement[] localizationCheckList = new ExtendedWebElement[menuLinks.size()];
        localizationCheckList = menuLinks.toArray(localizationCheckList);
        L10Nparser.checkMultipleLocalization(localizationCheckList, false);
        L10Nparser.saveLocalization();

So I think in case of List of webelements it should create a keys like given below
menulinks1
menulinks2
menulinks3

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/carina/pull/1321
