### ISSUE TITLE
AbstractApiMethodBase.java，when invoke setBodyContent  ,has error  ,can  help me?

### ISSUE THREAD

**Issue by littleshao** [qaprosoft/carina#1294]
`String test= "{\n" +
				"      \"title\": \"Test\",\n" +
				"      \"body\": \"ABCDE\",\n" +
				"      \"userId\": 6\n" +
				"}";
		System.out.println("++++++++++++++++++++++" + test);
		Map<String,String> cookik = new HashMap();
		cookik.put("session","test");
		apiMethodImp.setCookies(cookik);
		apiMethodImp.setBodyContent(test);
		Response rs = apiMethodImp.callAPI();`

`Body:
{
      "title": "Test",
      "body": "ABCDE",
      "userId": 6
}

**_2021-03-24 17:09:58 Messager [main] [INFO]
INFO: TEST [carina] FAILED at [17:09:58 2021-03-24] - Don't know how to encode {
      "title": "Test",
      "body": "ABCDE",
      "userId": 6
} as a byte stream.`_**

**Comment by DenisPitsul2020** [comment]
@littleshao what is this class AbstractApiMethodBase.java? There is no such class in Karina.
There is AbstractApiMethodV2? You should extends from this one.

**Comment by SergeiZagriychuk** [comment]
@littleshao I tried to set your message body in my test api method and I haven't got error like yours.
```String test = "{\n" + " \"title\": \"Test\",\n" + " \"body\": \"ABCDE\",\n" + " \"userId\": 6\n" + "}";
		api.setBodyContent(test);```

```Request URI:	https://jsonplaceholder.typicode.com/users
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Multiparts:		<none>
Cookies:		<none>
Headers:		Accept=*/*
				Content-Type=application/json; charset=UTF-8
Body:
{
    "title": "Test",
    "body": "ABCDE",
    "userId": 6
}
HTTP/1.1 201 Created```
Make sure you used "Content-Type=application/json" in your api method.
If error happens again please share contents of your apiMethodImp class.
