### ISSUE TITLE
Not able to run web tests via Zebrunner's launcher on SauceLabs selenium grid

### ISSUE THREAD

**Issue by SergeyBrenko** [qaprosoft/carina#1296]
**Description**
An attempt to launch web tests on SauceLabs selenium grid fails with the following error:
```
org.openqa.selenium.WebDriverException: Unable to parse remote response:
Misconfigured -- Mixed Capabilities Error.
W3C keys (platformName/browserVersion) were detected alongside JWP keys (platform/version).
To fix this, replace all JWP keys with W3C keys.
The following desired capabilities were received:
{'acceptInsecureCerts': True,
 'acceptSslCerts': True,
 'browserName': 'chrome',
 'carinaTestRunId': 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXb63bce55',
 'chrome.switches': ['--start-maximized',
                     '--ignore-ssl-errors'],
 'enableVideo': True,
 'goog:chromeOptions': {'args': ['test-type',
                                 '--lang=en_US'],
                        'extensions': [],
                        'prefs': {'intl.accept_languages': 'en_US'}},
 'name': 'default',
 'platformName': '*',
 'provider': 'SAUCELABS',
 'takesScreenshot': False,
 'version': ''}
```
**Steps to reproduce**
1. Obtain credentials to  SauceLabs account. You can either register a new account or contact me to get my credentials.
2. Register new workspace in Zebrunner.
3. Configure SauceLabs integration in Zebrunner with credentials from point 1.
4. Navigate to 'test run' page in Zebrunner
5. Open Launcher popup
6. Select 'Carina WEB' suite and launch it.

Actual results: all the tests from the suit fail with the error depicted above.
Expected results: test suit executed successfully

**Notes**
I've made a trivial attempt to fix the issue. My changes can be found here - https://github.com/qaprosoft/carina/commit/746c841f05c29d451f3b537a558f6f2e9b24c131

**Comment by vdelendik** [comment]
@DenisPitsul2020, let's reorganize AbstractCapabilities.java logic in such way:
1. capabilities.platformName has higher priority. If it is available we shouldn't set just platform
```
capabilities.setPlatform(Platform.extractFromSysProperty(platform));
```
2. capabilities.browserVersion has higher priority. If it is available we shouldn't set just version
```
        // Selenium 3.4 doesn't support '*'. Only explicit or empty browser version should be provided
        String browserVersion = Configuration.get(Parameter.BROWSER_VERSION);
        if ("*".equalsIgnoreCase(browserVersion)) {
            browserVersion = "";
        }
        capabilities.setVersion(browserVersion);
```
3. do not setVersion if it is empty

**Comment by DenisPitsul2020** [comment]
Resolved: https://github.com/qaprosoft/carina/pull/1297, 
you can test it on 7.0.3-SNAPSHOT

**Comment by vdelendik** [comment]
closing the ticket to start QA validation
