### ISSUE TITLE
provide runtime method to register app_version/build number

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1298]
We have to implement static setBuild in Configuration.java class.
This method should put into R.CONFIG new value for APP_VERSION key and register as zebrunnre reporting testrun artifact if not empty.
Also we have to add this new method into the migration steps (maybe new doc ticket needed for that). Among recommendations replace all project calls
```
R.CONFIG.put(Parameter.APP_VERSION.getKey(), value);
to
Configuration.setBuild(value);
```

**Comment by vdelendik** [comment]
done except adding migration steps

**Comment by okamara** [comment]
@vdelendik could you please add carina version and details for verification the ticket.

**Comment by okamara** [comment]
Verified. Fixed.
![](https://files.slack.com/files-pri/T4E815KGA-F020ZL4076C/screenshot_2021-04-28_at_15.02.39.png)
