### ISSUE TITLE
unit tests modify some files mistakenly

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1302]
after compilation it was discobered that such files are marked as modified:
modified:   carina-utils/src/test/resources/zip/textFile.txt                                                                                                                                                       modified:   carina-utils/src/test/resources/zip/zipFile.zip 

unit tests has to be adjusted to operate with this files but not modify... If thise files are generated automatically and not needed we can remove them and add into the .gitignore

**Comment by DenisPitsul2020** [comment]
Removed files and added names to .gitignore: https://github.com/qaprosoft/carina/pull/1303
