### ISSUE TITLE
Driver initialized in BeforeClass doesn't close after class tests have finished.

### ISSUE THREAD

**Issue by DimaGrinevich** [qaprosoft/carina#1306]

**Comment by DimaGrinevich** [comment]
Driver initialized in @BeforeTest should be closed after completing all tests from current <test></test>.
Driver initialized in @BeforeClass should be closed after all tests from class are complete.
Test code introduced in comments in https://github.com/qaprosoft/carina/pull/1304

**Comment by okamara** [comment]
@DimaGrinevich could you please verify and close this ticket
