### ISSUE TITLE
Add Azure Storage support

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [qaprosoft/carina#1324]
**Describe the solution you'd like**
Add the ability to download files from Azure Storage

**Additional context**
It would be useful if Carina automatically download the artifacts when apk/ipa files are stored on Azure storage

**Comment by vdelendik** [comment]
merged. changes can be tested using 7.1.5-SNAPSHOT core build.
also submitted #1331

**Comment by vdelendik** [comment]
@Ashraf-Ali-aa, 7.1.6-SNAPSHOT is the latest core version with your changes...
Note: it is not final and might be rebuilt several times so better not to use on prod to avoid regression failures.
