### ISSUE TITLE
Add possibility to run Fuzz tests on mobile cloud

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#135]
details: https://www.blackhat.com/docs/eu-15/materials/eu-15-Blanda-Fuzzing-Android-A-Recipe-For-Uncovering-Vulnerabilities-Inside-System-Components-In-Android-wp.pdf

**Comment by deNatallia** [comment]
UA repo. branch: fuzztest

**Comment by vdelendik** [comment]
closing as won't fix as of now
