### ISSUE TITLE
bump up to the latest RELEASE version for carina and zebrunner agent

### ISSUE THREAD

**Issue by DimaGrinevich** [qaprosoft/carina#1360]
https://github.com/qaprosoft/carina/pull/1355

**Comment by vdelendik** [comment]
as we finished with huge refactoring of archetype and carina-demo project we can try again switch the the latest RELEASE version for both dependencies.
Risks of the compilation failure is low now and we can support jumping to new versions without extra archetype release cycle

**Comment by vdelendik** [comment]
done. all components will try to use latest RELEASE as an experiment for 7.1.x version
