### ISSUE TITLE
support custom mobile capabilities logic on carina level: fullResetBeforeSuite

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#184]
there is standard fullReset capability which guarantee that app is uninstalled completely and cache is cleaned. Using this capability we can successfully override custom install/uninstall logic using direct adb calls (already removed from carina).
But negative aspect in this capability is that based on driver_mode we always reinstall application on the same device.
To minimize copy operation I proposed to add new capability:
-fullResetBeforeSuite

if it is true MobileCapabilityMatcher:
1. when we request device at first and capabilities matchers are satisfied then we convert this capability to standard
fullReset=true
2. remember device udid into local storage
3. During next attempt to open session on the same device do not transfer fullReset=true.

As result we will clean app/cache only at once during test suite start.

**Comment by vdelendik** [comment]
there is no way to handle it on selenium-grid custom proxy level as it doesn't know requester details. But at the same time it can be integrated into the IDriverPool and maybe IDevicePool

**Comment by khegor** [comment]
done
https://github.com/qaprosoft/carina/pull/712/files

**Comment by vdelendik** [comment]
closing as next changes expected to be delivered on carina-grid independent project
