### ISSUE TITLE
Take screenshots on Assertion failures and getting Exceptions

### ISSUE THREAD

**Issue by dmitry-minchuk** [qaprosoft/carina#196]
It would be useful if we can get actual screenshots exactly on failing step, not only on ExtendedWebElement and TestListener events.

For example: if I have try/finally logic with some assertions in try{...} block and some actions in finally{...} block, and one assertion fails in try{...} - I'll get screenshot on the last page of finally{...} block, which is not related to the failing reason. The same situation with exceptions.

**Comment by vdelendik** [comment]
review possibilities of new webdriver listener to handle different  exceptions and generate screenshots

**Comment by vdelendik** [comment]
5.2.3.75+ could make a screenshot asap right after each webdriver exception on any action
