### ISSUE TITLE
Swipe from MobileUtils doesn't work.

### ISSUE THREAD

**Issue by 7kov** [qaprosoft/carina#200]
Swipe from MobileUtils doesn't work. Example of logs:

sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) java.lang.reflect.Constructor.newInstance(Constructor.java:423) org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:215) org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:167) org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40) org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:82) org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:45) org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164) io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89) org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646) io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42) io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1) io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1) io.appium.java_client.PerformsTouchActions.performTouchAction(PerformsTouchActions.java:41) io.appium.java_client.TouchAction.perform(TouchAction.java:325) com.qaprosoft.carina.core.foundation.utils.mobile.MobileUtils.swipe(MobileUtils.java:447) com.qaprosoft.carina.core.foundation.utils.mobile.MobileUtils.swipeUntilElementPresence(MobileUtils.java:409) com.qaprosoft.carina.core.foundation.utils.mobile.MobileUtils.swipeUntilElementPresence(MobileUtils.java:380) com.myfitnesspal.refactored.gui.mobile.android.phone.diary.DiaryPage.clickNutritionBottomButton(DiaryPage.java:213) com.myfitnesspal.refactored.diary.DiaryTabTest.otherScreensTest(DiaryTabTest.java:34) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84) org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:200) com.qaprosoft.zafira.listener.ZafiraListener.run(ZafiraListener.java:502) sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) java.lang.reflect.Method.invoke(Method.java:498) org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:212) org.testng.internal.Invoker.invokeMethod(Invoker.java:707) org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901) org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231) org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127) org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111) org.testng.TestRunner.privateRun(TestRunner.java:767) org.testng.TestRunner.run(TestRunner.java:617) org.testng.SuiteRunner.runTest(SuiteRunner.java:348) org.testng.SuiteRunner.access$000(SuiteRunner.java:38) org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382) org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64) java.util.concurrent.FutureTask.run(FutureTask.java:266) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) java.lang.Thread.run(Thread.java:748)

**Comment by vdelendik** [comment]
set of improvements and fixes for iOS swipes are available in 3.2.2.240-SNAPSHOT core build.
We still experiment with duration and default swipe sizes for iOS...
