### ISSUE TITLE
How detect which version is last stable

### ISSUE THREAD

**Issue by hanushs** [qaprosoft/carina#202]
Hello.
I didn't know how to ask question except creating ticket...maybe it is a stupid Q, but how i identify what last version STABLE version i can pull from Nexus?

**Comment by hursevich** [comment]
Hello, @hanushs you can track https://mvnrepository.com/artifact/com.qaprosoft/carina-core, we are releasing stable builds to Maven Central.

**Comment by hanushs** [comment]
Thank. Then i was on right way!! Just was making sure!

**Comment by vdelendik** [comment]
@hanushs documentation, release notes etc should be published in Jan-18.
Press-releases supposed to be published here: http://www.carina-core.io/

**Comment by hanushs** [comment]
@vdelendik thank you! Will wait! Would be nice guys if you could design the diagram of classes involved and they purpose on the test start up!!!
