### ISSUE TITLE
Test name in zafira doesn't correspond to test logs and error stacktrace

### ISSUE THREAD

**Issue by SergeiZagriychuk** [qaprosoft/carina#206]
Test run link: https://ua.qaprosoft.com/zafira/#!/tests/runs/9432
Test with name "Dashboard graphs and summary labels - testGraphOfCaloriesYearly" shows artifacts and stacktrace for "Media Upload - testImageUpload".
Actually "Dashboard graphs and summary labels - testGraphOfCaloriesYearly" passed and "Media Upload - testImageUpload" failed
[console_output.txt](https://github.com/qaprosoft/carina/files/1568380/console_output.txt)
[test_logs.txt](https://github.com/qaprosoft/carina/files/1568381/test_logs.txt)

**Comment by vdelendik** [comment]
can't reproduce
