### ISSUE TITLE
How to execute tests without Selenium hub

### ISSUE THREAD

**Issue by hanushs** [qaprosoft/carina#228]
Hello
This is not a ticket. Just a question, since i didn't find where to ask questions.
When we configure Carina we need specify <selenium_host> property. Is there a chance to run a test on local selenium standalone specified in path? Or we always need make up hub?

P.S. As an improvement would be nice if you guys could do group on https://gitter.im/ and redirect there everybody, who has question, instead of creating tickets for question.

Thank you

**Comment by vdelendik** [comment]
Alex, please take a look and explain howto run tests without hub. It seems like we provide instruments to start hub even locally and never think about direct selenium standalone server

**Comment by vdelendik** [comment]
there is easy way to setup full test automation solution in one click using docker, selenoid etc.
No need to support direct web driver creation which require extra configuration steps on local machine
