### ISSUE TITLE
ExtendedElementLocator throws error in methods .isElementPresent() and .clickIfPresent() if element not found

### ISSUE THREAD

**Issue by szagriychuk-mfp** [qaprosoft/carina#234]
Error has following stacktrace:

> [ExtendedElementLocator.java] [1] [ERROR] Unable to find element: no such element: Unable to locate element: {"method":"id","selector":"agree"}
  (Session info: chrome=64.0.3282.119)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.02 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.2.0', revision: '8c03df6', time: '2017-03-02 09:34:51 -0800'
System info: host: 'HOST-NAME', ip: 'XXX.XXX.XXX.XXX', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_91'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f), userDataDir=C:\Users\UserName\AppData\Local\Temp\scoped_dir12272_29763}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=64.0.3282.119, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: dc4cc63090d56769e1228ae1bf7b505c
*** Element info: {Using=id, value=agree}
Command duration or timeout: 0 milliseconds

**Comment by vdelendik** [comment]
fixed in 5.2.2.47+ core build
