### ISSUE TITLE
Can't run tests with extra driver

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/carina#261]
1. driverFactory 49
switch (Configuration.getDriverType())
-> reuse desired capabilities values to determine type

2. ChromeCapabilities->getCapability (32 line)
analyze howto split caps init from config and desired list only
AbstractCapabilities.initCapabilities
for (Map.Entry<String, String> entry : capabilitiesMap.entrySet()) {

3. ExtendedElementLocator (111 line)
WebDriver driver = DriverPool.getDriver();
why default driver here?

**Comment by vdelendik** [comment]
fixes should be available in 5.2.3.56 core build. pay attention that capabilities should be generated using general method outside of carina!
