### ISSUE TITLE
Some tests are displayed with name=null, without Demo and Log in Zafira

### ISSUE THREAD

**Issue by deNatallia** [qaprosoft/carina#264]
Some tests are displayed with name=null, without Demo and Log in Zafira. And some of this tests are already exist in list with properly name and Demo/Log.
**It happens when rerun failures is executed**

It seems TestNamingUtil class need to be checked.

**Comment by vdelendik** [comment]
due to the recent 5.2.3.xx core changes issue with logs absence became much more annoying

**Comment by vdelendik** [comment]
fixed in 5.2.3.96+
