### ISSUE TITLE
Method getAttribute doesn't work 

### ISSUE THREAD

**Issue by KirillBugrim** [qaprosoft/carina#311]
Element has some attribute "value" in appium's tree. If I use Carina's method getAttribute("value"), method return null, but If I use Selenium's method getAttribute("value"), method return correct value.
For example: 
someExtendedWebElement.getAttribute("value") will return null;
someExtendedWebElement.getElement().getAttribute("value") will return correct value;
Carina-version 5.2.3.384-SNAPSHOT

**Comment by vdelendik** [comment]
fixed in 5.2.4.xx release
