### ISSUE TITLE
Remove extra logs org.openqa.selenium.remote.Augmenter

### ISSUE THREAD

**Issue by VitaliLiavitski** [qaprosoft/carina#320]
If Element is not clickable , we can see logs, but finally element was clicked :

element 'qqqqBtn (By.xpath: .//input[@name='qqqq' and @value='QQQQ'])' is not clicked!
May 23, 2018 4:05:46 PM org.openqa.selenium.remote.Augmenter extractRemoteWebDriver
WARNING: Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only (instance class was: class com.sun.proxy.$Proxy31)
May 23, 2018 4:05:49 PM org.openqa.selenium.remote.Augmenter extractRemoteWebDriver
WARNING: Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only (instance class was: class com.sun.proxy.$Proxy31)
May 23, 2018 4:05:52 PM org.openqa.selenium.remote.Augmenter extractRemoteWebDriver
WARNING: Augmenter should be applied to the instances of @Augmentable classes or previously augmented instances only (instance class was: class com.sun.proxy.$Proxy31)
2018-05-23 16:06:09 DriverListener [main] [INFO]PASS: element 'qqqqBtn' is clicked.

**Comment by vdelendik** [comment]
should be fixed in 5.2.3.96+
