### ISSUE TITLE
Create a plugin for Intellij, Eclipse

### ISSUE THREAD

**Issue by brutskov** [qaprosoft/carina#347]
It will improve a possibility to help user with ide internal features like set breakpoint with error throwing etc.

**Comment by vdelendik** [comment]
I'm thinking about online editor as part of infrastructure. 
https://github.com/qaprosoft/carina/issues/564
or even embedded eclipse as part of qps-infra

**Comment by vdelendik** [comment]
closing as dupe of https://github.com/zebrunner/zebrunner/issues/84
