### ISSUE TITLE
Typo in the Exception message. Should be `Please` instead of `Pleae`

### ISSUE THREAD

**Issue by aausianka** [qaprosoft/carina#354]
https://github.com/qaprosoft/carina/blob/87dbd0a1d7d742cf19cc1547eb0186b90fa6baf6/carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethodV2.java#L136

**Comment by aausianka** [comment]
Same in https://github.com/qaprosoft/carina/blob/87dbd0a1d7d742cf19cc1547eb0186b90fa6baf6/carina-api/src/main/java/com/qaprosoft/carina/core/foundation/api/AbstractApiMethodV2.java#L160

**Comment by vdelendik** [comment]
should be fixed in 5.2.4.102+
