### ISSUE TITLE
java.net.SocketException on attempt to execute swipeInDevice(ExtendedWebElement, Direction, int)

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/carina#362]
Carina 5.2.4.100
Appium 1.8.1
Mac OS

when i call following method:
com.qaprosoft.carina.core.foundation.utils.mobile.MobileUtils.swipeInDevice(ExtendedWebElement, Direction, int)

 i get:

INFO:SM-G935F - nerdwallet.qaprosoft.com:7412 TEST [Default test - onboardingStatementsDebtTest] STARTED at [20:49:08 2018-06-20]
2018-06-20 20:49:08 Messager [main] [INFO] [SM-G935F] 
INFO:SM-G935F - nerdwallet.qaprosoft.com:7412 TEST [Default test - onboardingStatementsDebtTest] SKIPPED at [20:49:08 2018-06-20] - java.net.SocketException: Connection reset
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'akratovich-NW1465', ip: 'fe80:0:0:0:97:e3b9:c930:4995%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '1.8.0_171'
Driver info: driver.version: AndroidDriver

com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringAppiumCommandExecutor.execute(EventFiringAppiumCommandExecutor.java:169)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.getSize(RemoteWebDriver.java:804)
com.qaprosoft.carina.core.foundation.utils.mobile.MobileUtils.swipeInDevice(MobileUtils.java:428)
com.qaprosoft.carina.core.foundation.utils.mobile.MobileUtils.swipeUp(MobileUtils.java:508)
com.qaprosoft.carina.core.foundation.utils.mobile.MobileUtils.swipeUp(MobileUtils.java:497)
com.nerdwallet.qa.mobile.mobilehome.gui.pages.android.profile.SettingsScreen.clickLogout(SettingsScreen.java:78)
com.nerdwallet.qa.mobile.mobilehome.services.AuthService.logout(AuthService.java:92)
com.nerdwallet.qa.mobile.authorization.onboardingstatements.OnboardingStatementsTest.enableStatements(OnboardingStatementsTest.java:63)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
org.testng.TestRunner.privateRun(TestRunner.java:767)
org.testng.TestRunner.run(TestRunner.java:617)
org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
org.testng.SuiteRunner.run(SuiteRunner.java:254)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
org.testng.TestNG.run(TestNG.java:1057)
org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by kolyakrasnik** [comment]
I'm getting the same on the debug mode for iOS. Tried with capabilities newCommandTimeout=180000 and  commandTimeouts=180000, the same result. Looks like the issue appears on calling getSize() method in  org.openqa.selenium.remote.RemoteWebDriver class.

**Comment by kolyakrasnik** [comment]
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteWindow.getSize(RemoteWebDriver.java:804)
com.qaprosoft.carina.core.foundation.utils.mobile.MobileUtils.swipe(MobileUtils.java:380)

**Comment by vdelendik** [comment]
fix available in 5.2.4.449-SNAPSHOT+

in release version fix will be in 5.2.4.102+
