### ISSUE TITLE
Add ability to create a new Driver on the same device

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/carina#364]
Currently if I want to create a new driver with custom capabilities (class : DriverPool.class, method: public static WebDriver getDriver(String name, DesiredCapabilities capabilities, String seleniumHost), line drv = createDriver(name, capabilities, seleniumHost, **DevicePool.getNullDevice()**),  the driver will be created on random free device because of **DevicePool.getNullDevice()** parameter. 
We need ability to specify desired device via capabilities.udid parameter.

**Comment by vdelendik** [comment]
reorganized Driver Factories removing device at all.
in case of restart on the same device I deliver capabilities with a single "uuid" value.
and when we receive in request capabilities with size = 1 and the only attribute "uuid" we can determine that this particular value should be appended

fix should be available in 6.0-beta13
6.0.206-SNAPSHOT+ core build
