### ISSUE TITLE
Support case insensitive locators for EWE and format functionality

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/carina#372]
it happens, that the same element may contains the same text, but in different cases (lower/upper/camel case)

to avoid that we use translate function of xpath. but ot's pretty complicated and not handy. aspecially if it is a dynamic locator:
"//*[contains(translate(@text, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), translate('%s', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'))]/preceding-sibling::*[contains(@resource-id, 'id/statValue')]"

if Carina has @CaseInsensetive annotation it'd be just great

**Comment by deNatallia** [comment]
implemented https://github.com/qaprosoft/carina/pull/376/files

**Comment by vdelendik** [comment]
feature is available 5.2.4.106+
Old notation to make xpath case insensitive:
"//[contains(translate(@text, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), translate('%s', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'))]/preceding-sibling::[contains(@resource-id, 'id/statValue')]"


new declaration:
@FindBy(xpath = "//*[contains(@resource-id, 'id/tabLayout')]//android.widget.TextView[@text='%s']")
@CaseInsensitiveXPath
private ExtendedWebElement tabItem;;
