### ISSUE TITLE
Command duration or timeout: 0 milliseconds

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/carina#378]
Expression like following:
element.clickIfPresent(3);

causes
05:57:17 2018-07-11 05:57:17 DriverListener [TestNG] [ERROR] [LG_G6] Session [8994f2ea-85b9-42bc-81b6-2537c5c51e38] was terminated due to TIMEOUT
05:57:17 Command duration or timeout: 0 milliseconds
05:57:17 2018-07-11 05:57:17 Screenshot [TestNG] [ERROR] [LG_G6] Unable to capture screenshot!
05:57:17 org.openqa.selenium.WebDriverException: Session [8994f2ea-85b9-42bc-81b6-2537c5c51e38] was terminated due to TIMEOUT
05:57:17 Command duration or timeout: 0 milliseconds

**Comment by vdelendik** [comment]
can't reproduce. capturing screenshot in recursive mode fixed. Fix should be available in 5.2.4.107+ core build
