### ISSUE TITLE
Carina 107: DriverFactory [TestNG] [ERROR]Unable to stream VNC: null

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/carina#387]
10:24:24 2018-07-13 10:24:23 DriverFactory [TestNG] [ERROR]Unable to stream VNC: null
10:24:24 java.lang.NullPointerException
10:24:24  at com.qaprosoft.carina.core.foundation.webdriver.core.factory.DriverFactory.streamVNC(DriverFactory.java:134)
10:24:24  at com.qaprosoft.carina.core.foundation.webdriver.core.factory.DriverFactory.create(DriverFactory.java:75)
10:24:24  at com.qaprosoft.carina.core.foundation.webdriver.DriverPool.createDriver(DriverPool.java:331)
10:24:24  at com.qaprosoft.carina.core.foundation.webdriver.DriverPool.getDriver(DriverPool.java:146)
10:24:24  at com.qaprosoft.carina.core.foundation.webdriver.DriverPool.getDriver(DriverPool.java:98)
10:24:24  at com.qaprosoft.carina.core.foundation.webdriver.DriverPool.getDriver(DriverPool.java:67)

**Comment by deNatallia** [comment]
added condition if (Reporter.getCurrentTestResult() != null) to streamVNC to avoid it for skipped tests
https://github.com/qaprosoft/carina/pull/391/files
