### ISSUE TITLE
make sure to support "Edge" name as well for desktop driver factory

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#393]
org.openqa.selenium.WebDriverException: unsupported browser: MicrosoftEdge (WARNING: The server did not provide any stacktrace information)
03:43:59 Command duration or timeout: 16 milliseconds
03:43:59 Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
03:43:59 System info: host: 'ip-10-253-1-194', ip: '10.253.1.194', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-1057-aws', java.version: '1.8.0_161'
03:43:59 Driver info: driver.version: RemoteWebDriver
03:43:59 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
03:43:59 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
03:43:59 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
03:43:59 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
03:43:59 	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
03:43:59 	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
03:43:59 	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
03:43:59 	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
03:43:59 	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
03:43:59 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
03:43:59 	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
03:43:59 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
03:43:59 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
03:43:59 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
03:43:59 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
03:43:59 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
03:43:59 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
03:43:59 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
03:43:59 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
03:43:59 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
03:43:59 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
03:43:59 	at com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringSeleniumCommandExecutor.execute(EventFiringSeleniumCommandExecutor.java:49)
03:43:59 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
03:43:59 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
03:43:59 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
03:43:59 	at com.qaprosoft.carina.core.foundation.webdriver.core.factory.impl.DesktopFactory.create(DesktopFactory.java:82)

**Comment by deNatallia** [comment]
browser name is transformed to lower case, added additional condition for IE and Edge browser if there is browserstack integration
https://github.com/qaprosoft/carina/pull/397/files
