### ISSUE TITLE
restore thread_id in logger messages

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#398]
we should again restore putting thread_id as part of log messages.
1) inspect all log4j.properties
2) keep only single one in valid place
3) make sure it has valid attribute to put thread id into the log message. If I remember something like this should be added in log4j.properties [%t]

**Comment by deNatallia** [comment]
Inserted thread_id in logger messages, changed the way of obtaining device name in logger messages
https://github.com/qaprosoft/carina/pull/400/files
