### ISSUE TITLE
hide below exception on making screenshot as warning

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#404]
20:56:20 org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: io.appium.uiautomator2.common.exceptions.TakeScreenshotException: Failed to capture a screenshot. Does the current view have 'secure' flag set?
20:56:20 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeDeviceScreenshot(ScreenshotHelper.java:70)
20:56:20 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(ScreenshotHelper.java:48)
20:56:20 	at io.appium.uiautomator2.utils.ScreenshotHelper.takeScreenshot(ScreenshotHelper.java:63)
20:56:20 	at io.appium.uiautomator2.handler.CaptureScreenshot.safeHandle(CaptureScreenshot.java:19)
20:56:20 	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:65)
20:56:20 	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:247)
20:56:20 	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:238)
20:56:20 	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
20:56:20 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
20:56:20 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
20:56:20 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
20:56:20 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
20:56:20 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
20:56:20 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
20:56:20 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
20:56:20 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
20:56:20 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
20:56:20 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
20:56:20 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
20:56:20 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
20:56:20 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
20:56:20 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
20:56:20 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
20:56:20 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
20:56:20 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
20:56:20 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
20:56:20 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
20:56:20 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
20:56:20 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
20:56:20 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
20:56:20 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
20:56:20 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
20:56:20 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
20:56:20 	at java.lang.Thread.run(Thread.java:764)
20:56:20  (WARNING: The server did not provide any stacktrace information)
20:56:20 Command duration or timeout: 0 milliseconds
20:56:20 Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
20:56:20 System info: host: 'fe32f0bede5a', ip: '172.20.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-119-generic', java.version: '1.8.0_151'
20:56:20 Driver info: io.appium.java_client.android.AndroidDriver
20:56:20 Capabilities {STF_ENABLED: true, app: /opt/apk/espn.ESPNRC.6.2.0...., appPackage: com.espn.score_center, autoGrantPermissions: true, automationName: uiautomator2, databaseEnabled: false, desired: {STF_ENABLED: true, app: /opt/apk/espn.ESPNRC.6.2.0...., autoGrantPermissions: true, automationName: uiautomator2, deviceName: ANY, deviceType: Phone, enableVNC: true, enableVideo: false, newCommandTimeout: 180, noSign: true, platformName: android, server:CONFIG_UUID: c17e7a7e-60a4-449f-b1ce-0c8..., udid: 9887a8445635425432, uninstall_related_apps: true}, deviceApiLevel: 26, deviceManufacturer: samsung, deviceModel: SM-G950U, deviceName: 9887a8445635425432, deviceScreenDensity: 640, deviceScreenSize: 1440x2960, deviceType: Phone, deviceUDID: 9887a8445635425432, enableVNC: true, enableVideo: false, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, newCommandTimeout: 180, noSign: true, pixelRatio: 3, platform: LINUX, platformName: Android, platformVersion: 8.0.0, server:CONFIG_UUID: c17e7a7e-60a4-449f-b1ce-0c8..., statBarHeight: 72, takesScreenshot: true, udid: 9887a8445635425432, uninstall_related_apps: true, viewportRect: {height: 2004, left: 0, top: 72, width: 1080}, warnings: {}, webStorageEnabled: false}
20:56:20 Session ID: d9e2ffea-f99f-473c-8907-8dd08ef4514e
20:56:20 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20:56:20 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
20:56:20 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
20:56:20 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
20:56:20 	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
20:56:20 	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
20:56:20 	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
20:56:20 	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
20:56:20 	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
20:56:20 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
20:56:20 	at com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringAppiumCommandExecutor.execute(EventFiringAppiumCommandExecutor.java:151)
20:56:20 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
20:56:20 	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:46)
20:56:20 	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
20:56:20 	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
20:56:20 	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:289)
20:56:20 	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.takeVisibleScreenshot(Screenshot.java:451)
20:56:20 	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.capture(Screenshot.java:312)
20:56:20 	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.capture(Screenshot.java:177)
20:56:20 	at com.qaprosoft.carina.core.foundation.webdriver.listener.DriverListener.captureScreenshot(DriverListener.java:218)
20:56:20 	at com.qaprosoft.carina.core.foundation.webdriver.listener.DriverListener.afterChangeValueOf(DriverListener.java:58)
20:56:20 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:56:20 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:56:20 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:56:20 	at java.lang.reflect.Method.invoke(Method.java:498)
20:56:20 	at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$0(EventFiringWebDriver.java:82)
20:56:20 	at com.sun.proxy.$Proxy43.afterChangeValueOf(Unknown Source)
20:56:20 	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.clear(EventFiringWebDriver.java:400)
20:56:20 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:56:20 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:56:20 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:56:20 	at java.lang.reflect.Method.invoke(Method.java:498)
20:56:20 	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
20:56:20 	at com.sun.proxy.$Proxy48.clear(Unknown Source)
20:56:20 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement$1.doType(ExtendedWebElement.java:1567)
20:56:20 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.executeAction(ExtendedWebElement.java:1385)
20:56:20 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.overrideAction(ExtendedWebElement.java:1493)
20:56:20 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1462)
20:56:20 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.type(ExtendedWebElement.java:689)
20:56:20 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.type(ExtendedWebElement.java:677)
20:56:20 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.type(ExtendedWebElement.java:667)

**Comment by deNatallia** [comment]
WebDriverException was hide in Screenshot.capture()
https://github.com/qaprosoft/carina/pull/413/files
