### ISSUE TITLE
Create and publish detailed article about CustomTypePageFactory usage

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#407]
Current mobile automation doc doesn't have information about one of the most popular carina pattern which allow to declare single testcase scenarion in test java class but reuse different pages implementations at run-time.
Please review below old steps and put much better article on corrent documentation carina portal.
https://github.com/qaprosoft/carina-demo/wiki/Mobile-automation#customtypefactory-and-devicetype

**Comment by deNatallia** [comment]
added description and examples of using CustomTypePageFactory
https://github.com/qaprosoft/carina/pull/408
