### ISSUE TITLE
Create isAppRunning() in MobileUtils

### ISSUE THREAD

**Issue by deNatallia** [qaprosoft/carina#414]
Wait until Appium bug is fixed:
https://github.com/appium/java-client/issues/854
https://github.com/appium/java-client/issues/821

and try to create isAppRunning() method

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/carina/blob/e0da1cccdee93488ddc75f4d11dcc38b913b4ff6/carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/utils/mobile/IMobileUtils.java#L771

should be delivered in 6.1.21+
