### ISSUE TITLE
official documentation page is inconsistent 

### ISSUE THREAD

**Issue by ABialkevich** [qaprosoft/carina#448]
=== Official documentation ===
http://qaprosoft.github.io/carina/configuration/#environment-specific-configuration
env=PROD
STAG.url=http://stag-app-server.com
PROD.url=http://prod-app-server.com
And get env-specific argument in test the following way:
Configuration.getEnvArg("url")
=== Current method ===
At the moment setPageUrl method has Configuration.getEnvArg("base");

**Comment by vdelendik** [comment]
fixed
