### ISSUE TITLE
Support web mobile execution on real devices

### ISSUE THREAD

**Issue by ABialkevich** [qaprosoft/carina#461]
Support web mobile execution on real devices

**Comment by vdelendik** [comment]
2018/10/02 15:57:44 [4398948] [0.00s] [SESSION_ATTEMPTED] [name] [172.21.0.1] [QPS-HUB-*] [selenium-hub:4444] [-] [1] [-]
2018/10/02 15:57:44 [4398953] [0.00s] [SESSION_ATTEMPTED] [name] [172.21.0.1] [QPS-HUB-*] [selenium-hub:4444] [-] [1] [-]
2018/10/02 15:57:50 [4399018] [0.00s] [UNSUPPORTED_BROWSER] [name] [192.168.88.112] [Safari] [-] [-] [-] [-]
2018/10/02 15:57:50 [4399024] [0.00s] [UNSUPPORTED_BROWSER] [name] [192.168.88.112] [Safari] [-] [-] [-] [-]

**Comment by vdelendik** [comment]
in 6.1.20+ improved carina and embedded QPS-HUB proxy to run mobile web tests:
Android + chrome and iOS + Safari works great.
rest of browsers supported to transfer app_package and app_activity to launch browsers but some extra problems with elements detection is discovered. It will be tracked by other issue: https://github.com/qaprosoft/carina/issues/717
