### ISSUE TITLE
Add support for browser localization

### ISSUE THREAD

**Issue by SantiagoPass** [qaprosoft/carina#499]
We are testing how the page works when the browser is set into different languages. But we are not able to start the browser in a specific language.

Will be great if you can adjust the code so we could easily start localized browser as well without extra capabilities generation. Adding, for example, a new property like browser_locale into _config.properties.

I attached an e-mail thread related to this topic.

[Directly Mail - RE_ Request from [www.carina-core.io].pdf](https://github.com/qaprosoft/carina/files/2534610/Directly.Mail.-.RE_.Request.from.www.carina-core.io.pdf)

**Comment by vdelendik** [comment]
feature should be available in 6.0 core generation. ETA: Nov, 7

**Comment by vdelendik** [comment]
changes for FF and Chrome are accessible in 5.3.2.127+

doc: http://qaprosoft.github.io/carina/configuration/
look for "browser_locale" property
