### ISSUE TITLE
in hybrid app,how carina switch to webview? thanks

### ISSUE THREAD

**Issue by littleshao** [qaprosoft/carina#503]
I can't find a way

**Comment by Litsvin** [comment]
Good time of a day. @littleshao !

To set desired context you might try following:

	public static void switchContext() {
		WebDriver drv = DriverPool.getDriver();
		if (drv instanceof EventFiringWebDriver) {
			drv = ((EventFiringWebDriver) drv).getWrappedDriver();
		}
		AppiumDriver<?> driver = (AppiumDriver<?>) drv;
		try {
			driver.context(desiredContext);
		} catch (Exception e) {
			//Your logic here...
		}
	}

Where 'desiredContext' is a String containing context's name;

To get a set of existing contexts you may use:
java.util.Set<String> contextNames = ((AppiumDriver<?>) driver).getContextHandles();
