### ISSUE TITLE
Connection reset on attempt to perform MobileUtils.tap(x, y, timeout)

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/carina#504]
carina 5.3.2.126

2018-11-02 18:32:16 Messager [main-1] [ERROR] [Android SDK built for x86] FAIL: Tap on X:'720' Y:'1305' was not executed.
2018-11-02 18:32:36 Messager [main-1] [INFO] [Android SDK built for x86] INFO: Android SDK built for x86 - emulator-5554 TEST [Default test - linkTUAccountFromFeedTest] FAILED at [18:32:36 2018-11-02] - java.net.SocketException: Connection reset
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'user-NW1465', ip: 'fe80:0:0:0:e2:423b:9cf0:9b2c%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '1.8.0_171'
Driver info: driver.version: AndroidDriver

com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringAppiumCommandExecutor.execute(EventFiringAppiumCommandExecutor.java:169)
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
io.appium.java_client.PerformsTouchActions.performTouchAction(PerformsTouchActions.java:41)
io.appium.java_client.TouchAction.perform(TouchAction.java:187)
com.qaprosoft.carina.core.foundation.utils.mobile.MobileUtils.tap(MobileUtils.java:150)

**Comment by vdelendik** [comment]
won't fix. That's usually means that server is overloaded and connections can't be established with proper quality
