### ISSUE TITLE
Add possibility to create List<ExtendedWebElement> using dynamic locator

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/carina#537]
Currently i'm able to do like this:

@FindBy(xpath = "//*[@text = '%s']")
ExtendedWebElement element;

and i want to create
@FindBy(xpath = "//*[@text = '%s']")
List<ExtendedWebElement> elements;

**Comment by vdelendik** [comment]
that's already supported:)
Example:
    @FindBy(xpath = "//android.view.ViewGroup")
    protected List<ExtendedWebElement> viewGroupElements;
