### ISSUE TITLE
3 drivers for one test, when only one driver is actually used (android)

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/carina#542]
carina 5.3.3.128

in zafira i see as on screenshot
![screen shot 2018-11-19 at 3 40 39 pm](https://user-images.githubusercontent.com/18280686/48707777-926cc080-ec11-11e8-836d-544496e35560.png)

no additional drivers were used

**Comment by vdelendik** [comment]
fixed also in 5.3.3.129+ carina
