### ISSUE TITLE
6.x: jira updater should be refactored

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#544]
current implementation of IJiraUpdater shouldn't have any reference onto the ITestContext.

only ISuite will be accessible in new core generation. let's investigate if we can reorganize integration and deliver it as functional interface with default implementation

**Comment by vdelendik** [comment]
feature is not valuable and should be removed:
1) remove IJiraUpdater interface and all occurences
2) remove JIRA_UPDATER("jira_updater"), JIRA_USER("jira_user") and JIRA_PASSWORD("jira_password")
3) remove net.rcarz dependency from carina-utils

**Comment by dprymudrau** [comment]
core build number:
6.4.41-SNAPSHOT

**Comment by okamara** [comment]
Verified.
