### ISSUE TITLE
Necessary adding filter for language and locale

### ISSUE THREAD

**Issue by VitaliLiavitski** [qaprosoft/carina#546]
Necessary adding filter for language and locale

**Comment by vdelendik** [comment]
added testrail filters by language and locale/
feature will be available in 6.0.185-SNAPSHOT+ builds.

example of the usage can be found here:
https://github.com/qaprosoft/carina/blob/a0be7e9f87bc766b3f5245b599ec4f973903f74d/carina-reporting/src/test/java/com/qaprosoft/carina/core/foundation/reporting/TestRailTest.java#L166
