### ISSUE TITLE
JDK upgrade

### ISSUE THREAD

**Issue by nazarenkAV** [qaprosoft/carina#551]
As a user I want to use features from JDK 11. So, please support it.

**Comment by leonpros** [comment]
I believe that as a user, you import the carina project to your test infrastructure where you can use JDK 11.
I believe that forcing JDK on carina infrastructure may cause many working projects to stop working as mostly, JDK 11 is not supported in most of the companies (yet).
While you can use JDK 11 with backward compatibility to JDK 8, it cannot be vise versa.

Please correct me if i am wrong

**Comment by vdelendik** [comment]
moving even carina-grid onto the latest JDK produced a lot of troubles. And in carina-grid we control everything including deployment in scope of the container. Moving carina-core can be too risky

**Comment by vdelendik** [comment]
whole our zebrunner infrastructure where carina is widely used is already on jdk 11 so we switched to this version carina core as well in upcoming release: https://github.com/qaprosoft/carina/commit/2157100624c6d08f01a5f6aa2f12ab4496fb91c2
