### ISSUE TITLE
Drivers are not closed during executing on one device in CI using dataprovider

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/carina#552]
org.openqa.selenium.WebDriverException: org.openqa.selenium.WebDriverException: cannot create session QPS-HUB-* on any hosts after 1 attempt(s) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 300.00 seconds

**Comment by vdelendik** [comment]
root cause - restartDriver logic which was invoked in your test. Fully redesigned Driver Factory removing bottle-neck
