### ISSUE TITLE
Add new parameters for video recording to match appium 1.10 implementation

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/carina#566]
In appium 1.10 were added new screen recording options. We need to improve carina to be able to use these parameters. https://github.com/appium/appium-xcuitest-driver/commit/714cc44b1f2fc155b3553199d2a01485167166d8

**Comment by kolyakrasnik** [comment]
6.0.348-SNAPSHOT
All the parameters are work as expected, except fps.
Related appium bug:
https://github.com/appium/appium/issues/12067

**Comment by vdelendik** [comment]
6.0.10+
