### ISSUE TITLE
Use MutableCapabilities instead of DesiredCapabilities

### ISSUE THREAD

**Issue by leonpros** [qaprosoft/carina#569]
WebDriver initialization should be updated to using `MutableCapabilities` (FirefoxOptions, ChromeOptions etc.) instead of DesiredCapabilities.

This will also prevent from the warning in logs
> INFO: Using `new FirefoxOptions()` is preferred to `DesiredCapabilities.firefox()`

example:
`
FirefoxOptions firefoxOptions = new FirefoxOptions();
firefoxOptions.setCapability(CapabilityType.TAKES_SCREENSHOT, false); firefoxOptions.setCapability(FirefoxDriver.PROFILE, profile);
`

**Comment by vdelendik** [comment]
too many changes in code. closing as won't fix so far
