### ISSUE TITLE
Hardcoded parameters in carina archetype (-Dname and -Durl)

### ISSUE THREAD

**Issue by ydaroshka** [qaprosoft/carina#582]
Entering custom project name and url don't appear in generated pom.xml file.

After using mvn archetype:generate command we are getting default values 
<name>Carina Demo</name>
<url>http://www.qaprosoft.com/</url>

**Comment by vdelendik** [comment]
still exists in 6.5 and 7.0

**Comment by vdelendik** [comment]
fixed. to test please genearete new project using RELEASE archetype and custom values for project name and url.
verify that new generated pom.xml file has provided name, url, groupId and artifactId
```
# create new empty folder and cd into it
mvn archetype:generate -DarchetypeGroupId=com.qaprosoft -DarchetypeArtifactId=carina-archetype -DarchetypeVersion=RELEASE -DgroupId=com.myorj -DartifactId=myproject -Dname="My Project" -Durl=http://myurl.com -Dversion=1.0
```

new generated project in a top of pom.xml should have:
```
	<groupId>com.myorj</groupId>
	<artifactId>myproject</artifactId>
	<version>1.0</version>
	<packaging>jar</packaging>
	<name>My Project</name>
	<url>http://myurl.com</url>
```

**Comment by okamara** [comment]
Verified. Done.
