### ISSUE TITLE
Device type is defined incorrectly in several cases for iOS/Android tests

### ISSUE THREAD

**Issue by rzubkouski** [qaprosoft/carina#590]
There is a number of iOS/Android tests (only 1 test method per one class) which is failing due to the following issue:
**There is no any class that satisfy to required conditions: [device type - DESKTOP]**

**Comment by vdelendik** [comment]
latest 6.0.5-SNAPSHOT has improvements into the driversPool cleanup.
I hope it should fix such kind of issues for multi-threading environments
