### ISSUE TITLE
Update appium java client to the latest version (7.0.0)

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/carina#618]
Update appium java client to 7.0.0 version. It will require at least video recording parameter updates due to https://github.com/appium/java-client/pull/1067/commits/28bc78c345d82385f92aa84e7be36bd7074f2a10?utf8=%E2%9C%93&diff=split
https://github.com/appium/java-client/releases/tag/v7.0.0

**Comment by kolyakrasnik** [comment]
PR: https://github.com/qaprosoft/carina/pull/619

**Comment by vdelendik** [comment]
merged
