### ISSUE TITLE
Create Zoom in/out in MobileUtils

### ISSUE THREAD

**Issue by alonhartman** [qaprosoft/carina#622]
As a user, I'd like to have the capability to zoom an element in and out.

**Comment by vdelendik** [comment]
@kolyakrasnik make sure to move code into IMobileUtils functional interface

**Comment by kolyakrasnik** [comment]
PR: https://github.com/qaprosoft/carina/pull/633, CARINA: 6.0.335-SNAPSHOT

**Comment by kolyakrasnik** [comment]
Yep, totally forgot about this interface. Thank's for the catch.

**Comment by vdelendik** [comment]
6.0.9-SNAPSHOT
