### ISSUE TITLE
Annoying INFO message: Value not resolved by key: PRODUCTION.url

### ISSUE THREAD

**Issue by ivansnytko** [qaprosoft/carina#629]
Carina6.0.8: I see a lot of annoying log messages in test logs:

06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-1-35] [WARN] [iPhone_8Plus] Value not resolved by key: PRODUCTION.url
06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-3-37] [WARN] [iPhone_6s_white] Value not resolved by key: PRODUCTION.url
06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-2-36] [WARN] [iPhone_6s_black] Value not resolved by key: PRODUCTION.url
06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-1-35] [WARN] [iPhone_8Plus] Value not resolved by key: PRODUCTION.url
06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-2-36] [WARN] [iPhone_6s_black] Value not resolved by key: PRODUCTION.url
06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-3-37] [WARN] [iPhone_6s_white] Value not resolved by key: PRODUCTION.url
06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-2-36] [WARN] [iPhone_6s_black] Value not resolved by key: PRODUCTION.url
06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-2-36] [WARN] [iPhone_6s_black] Value not resolved by key: PRODUCTION.url
06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-2-36] [WARN] [iPhone_6s_black] Value not resolved by key: PRODUCTION.url
06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-2-36] [WARN] [iPhone_6s_black] Value not resolved by key: PRODUCTION.url
06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-2-36] [WARN] [iPhone_6s_black] Value not resolved by key: PRODUCTION.url
06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-2-36] [WARN] [iPhone_6s_black] Value not resolved by key: PRODUCTION.url
06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-2-36] [WARN] [iPhone_6s_black] Value not resolved by key: PRODUCTION.url
06:22:31 2019-01-18 06:22:31 PlaceholderResolver [TestNG-tests-2-36] [WARN] [iPhone_6s_black] Value not resolved by key: PRODUCTION.url

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/carina/pull/632
