### ISSUE TITLE
API: Update JSONassert lib to latest version.

### ISSUE THREAD

**Issue by ABialkevich** [qaprosoft/carina#646]
At the moment with JSONassert (v 1.2.x) we are not able to match jsons with big nesting.
e.g
{
	"meta": xxx,
	"data": {
		"item": {
			"items": [
				[{
						"filed1": "xxx",
						"filed2": "xxx",
						"status": "ACTIVE",
						"status_history": [{
							"acc1": "xxx",
							"created": "xx",
							"id": "xxx,
							"message": xxx,
							"status": "xxx"
						}]
					},
					"xxx"
				],
				[{
						"filed1": "xxx",
						"filed2": "xxx",
						"status": "ACTIVE",
						"status_history": [{
							"acc1": "xxx",
							"created": "xx",
							"id": "xxx,
							"message": xxx,
							"status": "xxx"
						}]
					},
					"xxx"
				]
			]
		},
		"errors": {

		}
	}
}

**Comment by vdelendik** [comment]
after discussion using exact use-case we decided to skip jsonassetr upgrade as it leads to huge internal refactoring. So closing with resolution "won't fix" after confirmation with submitter
