### ISSUE TITLE
Implement findByImage strategy

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/carina#648]
Since java appium client 7.0.0 new strategy for finding elements has been added : findByImage. Let's add it to the carina framework 
https://github.com/appium/java-client/releases/tag/v7.0.0

**Comment by kolyakrasnik** [comment]
Ready for review https://github.com/qaprosoft/carina/pull/657

**Comment by kolyakrasnik** [comment]
Parameters to adjust recognition http://appium.io/docs/en/advanced-concepts/image-elements/

**Comment by vdelendik** [comment]
feature is available in 6.0.12-SNAPSHOT

detailed info:
http://qaprosoft.github.io/carina/automation/mobile/
- How to use Find by image strategy
