### ISSUE TITLE
Unable to capture correct full size browser screenshot on Mac OS

### ISSUE THREAD

**Issue by rkatuzhanets** [qaprosoft/carina#653]
FullSize screenshot capturing doesn't work on Mac OS system, as using of captureFullSize() method from com.qaprosoft.carina.core.foundation.webdriver.Screenshot class leads to capturing of only upper left corner of the page

 - Browsers: Chrome 71.0 | Firefox 65.0 | Safari 12.0
...

**Comment by vdelendik** [comment]
@rzubkouski is it fixed?

**Comment by vdelendik** [comment]
closing
