### ISSUE TITLE
APi validation error when comparing array's inside an array 

### ISSUE THREAD

**Issue by barakshr** [qaprosoft/carina#656]
Json example:  {values" : [[ 1, 1 ]]} 

When comparing this json with itself there will be a validation failure :
 'Expected array item '[1,1]' is missed in actual array'

Carina method that is used for validation is : 'JSONAssert.assertEquals(expectedRs, this.actualRsBody, new JsonKeywordsComparator(mode, validationFlags));'

From what i saw, the 'JsonKeywordsComparator' class causes the problem .
when i upgraded the Json assert library from 1.2.3 to 1.5.0 the problem didn't appear

**Comment by SergeiZagriychuk** [comment]
Unfortunately we can not migrate to jsonassert v1.5.0 as is.
jsonassert v1.5.0 uses library com.vaadin.external.google.android-json as dependency and this library has conflicts with org.json library which is used in other api framework features (in particular for validation by json schema of version draft06/07)

So I updated version of jsonassert to v1.5.0 but had to exclude com.vaadin.external.google.android-json. What didn't fix issue mentioned in the ticket.

If it's still critical for you to process json like that you can include com.vaadin.external.google.android-json v0.0.20131108.vaadin1 directly in your project's pom.xml. But you need to remember that it will break json schema validation functionality for schemas of version draft 06/07

cc @vdelendik
