### ISSUE TITLE
Unable to initialize driver on device

### ISSUE THREAD

**Issue by khegor** [qaprosoft/carina#669]
During job run, driver on different devices wasn't initialized, tests was skipped. Following information was logged: "Unable to initialize driver: ! UDID: ."

CARINA_CORE_VERSION=6.0.13

com.qaprosoft.carina.core.foundation.webdriver.core.factory.impl.MobileFactory.create(MobileFactory.java:223)
com.qaprosoft.carina.core.foundation.webdriver.core.factory.DriverFactory.create(DriverFactory.java:68)
com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.createDriver(IDriverPool.java:350)
com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:143)
com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:78)
com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:66)

sun.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
org.testng.TestRunner.privateRun(TestRunner.java:648)
org.testng.TestRunner.run(TestRunner.java:505)
org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

- Device: HTC_U_Ultra, Samsung_Galaxy_S7, Motorola_G4, Samsung_Galaxy_J7
- OS: Android 7.0, 8.0, 8.1.0
- Appium version 1.10.1
Same issue is for iOS:
- Device: iPhone 6s, 8
- OS: 12.1
- Appium version 1.10.1

**Comment by kolyakrasnik** [comment]
@vdelendik the issue is with lost retry count logic

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/carina/commit/c1eff35889b66c9d0cb07e89e071f7c94a7ab9a2
