### ISSUE TITLE
Fix nullPointer exception in case if device name is empty: ""

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/carina#673]
`07:59:56 java.lang.NullPointerException
07:59:56 	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.registerDevice(IDriverPool.java:547)
07:59:56 	at com.qaprosoft.carina.core.foundation.webdriver.core.factory.impl.MobileFactory.create(MobileFactory.java:221)
07:59:56 	at com.qaprosoft.carina.core.foundation.webdriver.core.factory.DriverFactory.create(DriverFactory.java:68)
07:59:56 	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.createDriver(IDriverPool.java:350)
07:59:56 	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:143)
07:59:56 	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:78)
07:59:56 	at com.qaprosoft.carina.core.foundation.webdriver.IDriverPool.getDriver(IDriverPool.java:66)
07:59:56 	at `

**Comment by vdelendik** [comment]
fix should be available in 6.0.16
