### ISSUE TITLE
Hub — provide the possibility of running mobile web tests

### ISSUE THREAD

**Issue by rzubkouski** [qaprosoft/carina#681]
According to the current approach, mobile web tests couldn't be executed since the application name should be determined. So it would be nice to have an opportunity to run either Android or iOS mobile web tests with an opportunity to choose specific device from the pool.

**Comment by vdelendik** [comment]
feature will be available in 6.1.20+
among supported device browsers are:
- chrome
- firefox
- safari
- edge
- opera, opera mini
- samsung native (sbrowser)
- yandex

PR: https://github.com/qaprosoft/carina/pull/709
