### ISSUE TITLE
mvn doesn't read user's custom -Dname and -Durl fields in Carina archetype

### ISSUE THREAD

**Issue by ydaroshka** [qaprosoft/carina#691]
**Describe the bug**
On setup Carina Carina archetype all user's custom fields are changed in  pom.xml file except 
-Dname and -Durl fields. 
for these two fields xml shows: ${text} 
**Logs/Links**
here are logs after executing mvn clean eclipse:eclipse  fro importing the project to eclipse: 
ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] The expression ${name} is deprecated. Please use ${project.name} instead. @
[ERROR] Resolving expression: ‘${name}’: Detected the following recursive expression cycle in ‘name’: [name] @
[WARNING] The expression ${url} is deprecated. Please use ${project.url} instead. @
[ERROR] Resolving expression: ‘${url}’: Detected the following recursive expression cycle in ‘url’: [url] @
@
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.ydaroshka:ad-test:1.0 (/Users/ydaroshka/ad-test/pom.xml) has 2 errors
[ERROR]     Resolving expression: ‘${name}’: Detected the following recursive expression cycle in ‘name’: [name] -> [Help 2]
[ERROR]     Resolving expression: ‘${url}’: Detected the following recursive expression cycle in ‘url’: [url] -> [Help 2]

**Comment by vdelendik** [comment]
fixed with 6.3.30 archetype. Both name and url are correctly detected and deployed to recently created project
