### ISSUE TITLE
Provide possibility of setting required tags directly in code

### ISSUE THREAD

**Issue by rzubkouski** [qaprosoft/carina#701]
According to the current implementation, tags could be defined for the specific test only by setting @TestTag annotation. It would be extremely useful to have an opportunity of determining necessary tags directly in test code as well.

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/zafira/pull/1540
https://github.com/qaprosoft/carina/pull/714

fixes should be available in 6.1.20+ carina and 4.0.52+ zafira and 4.0.56+ zafira-client
