### ISSUE TITLE
ui dump report for mobile runs should be published to S3 as artifact

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#703]
**Describe the bug**
Update procedure and reuse aws s3 artifacts publishing for each UI dump files if any.
For now they are accessible only as part of obsolete eTAFReport in jenkins which is inaccessible by default.
for details visit: https://github.com/qaprosoft/zafira/issues/900

**Comment by vdelendik** [comment]
logcat publish as artifacts as well if possible

**Comment by kolyakrasnik** [comment]
https://github.com/qaprosoft/carina/pull/725

**Comment by vdelendik** [comment]
done in 6.1.21+
