### ISSUE TITLE
Make sense to get rid of mandatory owner attribute in @MethodOwner

### ISSUE THREAD

**Issue by brutskov** [qaprosoft/carina#719]
The biggest part of test automation flow use primary method owner only, but it is not possible to assign test owner without "owner" attribute. Make sense to inject default "value" attribute which has an attachment to "owner" attribute to avoid code duplicate.

**Comment by vdelendik** [comment]
removing secondary method owner has bigger priority

**Comment by vdelendik** [comment]
let's think about this enhancement only after updating code in accordance with https://github.com/qaprosoft/carina/issues/736

**Comment by vdelendik** [comment]
@Boniara in 6.1.22 secondaryOwner parameter is removed. Please ping me to discuss this ticket.

**Comment by vdelendik** [comment]
new zebrunner agent has core functionality which satisfy these requirements. carina method owner still continue to be enhanced a little bit
