### ISSUE TITLE
Document Carina Debugging entry point

### ISSUE THREAD

**Issue by sspieker-cc** [qaprosoft/carina#721]
**Describe the solution you'd like**
Various changes to the a project that utilizes the Carina Framework for testing seems to have disabled or overridden the log4j logging options with no changes being applied to the maven carina template supplied files.  If there was a documented class that could be used for a debugging entry point we (QA Test devs) can follow the process from the onset and identify where there is an overlap in classes being provided and from where they are initialized would be ideal.

**Additional context**
This request is specifically for a documentation update regarding how to begin a debugging process where the carina framework is impacted by some dependencies in the testing project.  The first class that initializes the framework for the various types of tests such as GUI, API, Cucumber, DB or Mobile would be ideal with a quick example for good measure.

**Comment by DimaGrinevich** [comment]
#1290

**Comment by DimaGrinevich** [comment]
Need to check for language mistakes and text format
http://qaprosoft.github.io/carina/advanced/program_flow/
