### ISSUE TITLE
dragAndDrop method doesn't work for images in UI (Web) testing

### ISSUE THREAD

**Issue by HristoIvanovUpnetix** [qaprosoft/carina#737]
**Describe the bug**
When Actions class is used it has dragAndDrop method, but it crashes when ist's used for image. The action of drag&drop didn't happen.

**Logs/Links**
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'UXLT027', ip: '10.0.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_192'
Driver info: driver.version: EventFiringWebDriver

Web
 - Browser [e.g. chrome, firefox]
 - Version of Chrome - 75.0.3770.80
 - Version of Chrome - 67.0

**Comment by vdelendik** [comment]
drag and drop still need specific implementation for different architecture and application frameworks. there is no single way to cover everything. so no way to deliver it as carina code so far
