### ISSUE TITLE
Upgrade sonqrube version to 7.7 

### ISSUE THREAD

**Issue by ivan-dobrinov** [qaprosoft/carina#746]
At the moment the qaprosoft docker image of sonarqube installs SonarQube ver.5.6.7.
Is it possible to provide a qaprosoft image which builds SonarQube community ver.7.7 (that's the lataest one at the moment).

**Comment by vdelendik** [comment]
submitted ticket in better project: https://github.com/qaprosoft/qps-infra/issues/65.
this one can be closed
@ivan-dobrinov ^^^
