### ISSUE TITLE
Could NOT find resource [logback.groovy]

### ISSUE THREAD

**Issue by tbdyzm** [qaprosoft/carina#748]
I'm new to carina, when I run my test, console logs are like this:
15:15:07,813 |-INFO in ch.qos.logback.classic.LoggerContext[MyBatisDAOHelper] - Could NOT find resource [logback.groovy]
15:15:07,814 |-INFO in ch.qos.logback.classic.LoggerContext[MyBatisDAOHelper] - Could NOT find resource [logback-test.xml]
there is no problem with the test, but I don't kown what logback.groovy and logback-test.xml is, I never use them, I'm looking forward to your reply, thks
![1](https://user-images.githubusercontent.com/41499236/59491805-2954df00-8eba-11e9-91a9-a66487f5d733.png)

**Comment by vdelendik** [comment]
That’s info log message of the one of the resource(mybatis). It is not even a warning. Ignore it so far.
