### ISSUE TITLE
Rename test directory name not set in Thread.

### ISSUE THREAD

**Issue by nikitaqk** [qaprosoft/carina#749]
In ReportContext class, we are using renameTestDir() to rename the directory as "ABC", which it does. But when we go to the next step of execution the test logs and the screenshots of the next step is stored in Carina defined directory where it should be store in "ABC" directory. It is because in renameTestDir() the rename directory name "ABC" is not stored in the testDirectory thread.
 
![image](https://user-images.githubusercontent.com/50707127/59828751-53464f80-9359-11e9-89a8-308412bbb46f.png)

**Comment by kolyakrasnik** [comment]
Related PR https://github.com/qaprosoft/carina/pull/753

**Comment by kolyakrasnik** [comment]
@nikitaqk could you, please, try this snapshot build and let me know if it matches your purposes 6.1.525-SNAPSHOT

**Comment by kolyakrasnik** [comment]
The latest changes available with 6.1.528-SNAPSHOT. To set custom test dir name use method ReportContext.setCustomTestDirName("customName");

**Comment by vdelendik** [comment]
fix is available in 6.1.22-SNAPSHOT.
it should be included into 6.1.22 released build as well
