### ISSUE TITLE
Android devices are released a long period of time after a job aborting

### ISSUE THREAD

**Issue by khegor** [qaprosoft/carina#755]
Android devices are released a long period of time after a job aborting. The time of waiting (when devices will be available) is about 40 minutes. This issue was appeared when video recording and screenshots were enabled.

Device/OS: all android devices;
Appium version: 1.13.0.

It's look like Carina doesn't understand that devices are available, and think that somebody use them.

**Comment by vdelendik** [comment]
set of fixes are available in overall appium-device container to make it more stable. Also provided recommendation for private listeners howto minimize risks of the occupied devices
