### ISSUE TITLE
Requesting to integration of current carina with cucumber as a separate module.

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina#765]
Hi, 
Can you please help me with a merged code of current carina and cucumber module.
- There should be a facility that current carina/cucumber version gets updated then we can also update the same.
- The merged code should also help to Zafira and cucumber reporting.
- The merged code should be treated as a separate module.

**Comment by vdelendik** [comment]
TestNG+Cucumber carina runner is available again in snapshot core builds.
To enable it for your project we have:
1) declare carina-core 6.1.25-SNAPSHOT and carina-cucumber 1.0-SNAPSHOT as dependencies
https://github.com/qaprosoft/carina-demo/blob/40621d2dfff6a1592e8d70b82d53fa2e0ab6df9f/pom.xml#L37

2) create appropriate TestNG suite and java classes
https://github.com/qaprosoft/carina-demo/blob/cucumber/src/test/resources/testng_suites/cucumber-web.xml
https://github.com/qaprosoft/carina-demo/blob/cucumber/src/test/java/com/qaprosoft/carina/demo/CucumberWebSampleTest.java

3) Extend your cucumber test from CucumberBaseTest
https://github.com/qaprosoft/carina-demo/blob/40621d2dfff6a1592e8d70b82d53fa2e0ab6df9f/src/test/java/com/qaprosoft/carina/demo/CucumberWebSampleTest.java#L16

4) describe BDD methods as steps:
https://github.com/qaprosoft/carina-demo/blob/cucumber/src/test/java/com/qaprosoft/carina/demo/cucumber/steps/GSMArenaNewsSteps.java

5) describe features steps:
https://github.com/qaprosoft/carina-demo/blob/cucumber/src/test/resources/features/GSMArenaNews.feature

6) inject features and steps in your test class using @CucumberOptions annotation:
https://github.com/qaprosoft/carina-demo/blob/40621d2dfff6a1592e8d70b82d53fa2e0ab6df9f/src/test/java/com/qaprosoft/carina/demo/CucumberWebSampleTest.java#L7

As result you could execute cucumber-web.xml as regular TestNG but in additions to carina generate extended cucumber reports with features/steps/tags etc

![image](https://user-images.githubusercontent.com/4551455/61828594-bdc64000-ae6f-11e9-8536-cc372b7498a9.png)

**Comment by vdelendik** [comment]
done
