### ISSUE TITLE
improve amazon aws-java-sdk dependencies

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#782]
for now carina-aws-s3 include whole aws-java-sdk. We have to try to minimize number of dependencies using exact modules we need.
Among all dependencies in carina aws dependencies have too huge list of jars

**Comment by vdelendik** [comment]
6.1.25+
https://github.com/qaprosoft/carina/pull/786

**Comment by zssMostE** [comment]
will there be any bad effects about the huge list dependencies of carina aws ? @vdelendik
