### ISSUE TITLE
Error in TagManagerTest class of demo project

### ISSUE THREAD

**Issue by sumeshbabukonni** [qaprosoft/carina#787]
Steps to reproduce:
follow the instructions from
http://qaprosoft.github.io/carina/getting_started/
While importing the project in eclipse, there are three errors
![image](https://user-images.githubusercontent.com/798084/61724931-829f1080-ad8c-11e9-917a-2351a8d70c91.png)

**Comment by vdelendik** [comment]
issue is fixed in 6.1.22 archetype, documentation adjusted accordingly: http://qaprosoft.github.io/carina/getting_started/
thanks @sumeshbabukonni for your help
