### ISSUE TITLE
provide BDD documentation (cucumber)

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#789]
subj

**Comment by vdelendik** [comment]
done. newdocumentation should appear after releasing 7.0.0

**Comment by okamara** [comment]
@vdelendik where we should see this new documentation?

**Comment by okamara** [comment]
Documentation is verified in pull request. Need to check on release version.

**Comment by okamara** [comment]
Verified in git.
Cucumber report need to fix -> https://github.com/qaprosoft/carina/blob/master/docs/cucumber.md
<img width="1097" alt="Screen Shot 2021-01-26 at 2 14 12 PM" src="https://user-images.githubusercontent.com/32964663/105838222-dec99d00-5fe0-11eb-918c-2239d1baae49.png">

**Comment by vdelendik** [comment]
merged. @okamara, please review.

**Comment by okamara** [comment]
Images are fixed.
