### ISSUE TITLE
Adapt .openUrl() method of com.qaprosoft.carina.core.foundation.webdriver.DriverHelper.class for mobile device

### ISSUE THREAD

**Issue by shukal94** [qaprosoft/carina#792]
Please, provide the possibility of disabling maximize window actions while page opening on mobile devices as it causes unexpected driver exit in new chromedriver versions.

**Additional context**
faced with this issue on mobile web automation (chromedriver 76)

**Comment by vdelendik** [comment]
already fixed in 6.1.25
