### ISSUE TITLE
request to share access to append any arguments for the requested session via 'browser_args' parameter

### ISSUE THREAD

**Issue by alonhartman** [qaprosoft/carina#793]
Currently, it's impossible to pass parameters to the browser from the '_config.xml' file, I'd like for additional parameter in the config file named "browser_args" so it'll be possible to pass some params to the browser.
For example:
browser_args=--silent-launch,--no-startup-window,no-sandbox,headless

**Comment by vdelendik** [comment]
@alonhartman, in 6.2.618-SNAPSHOT core build chrome arguments/options improvements delivered:
you can override everything you need using comma separated args:
chrome_args=--lang=en,...

and experimental options: 
chrome_experimental_opts=w3c=false,...

**Comment by vdelendik** [comment]
6.2.28+
