### ISSUE TITLE
Add ability to start proxy on predefined list of ports

### ISSUE THREAD

**Issue by SergeiZagriychuk** [qaprosoft/carina#794]
We need this functionality to enable tests with proxy execution in multi-threaded mode. When entire infrastructure is distributed between several selenium boxes

to enable the feature next properties should be set:
-- not to use predefined single port
browsermob_port=NULL
-- range of ports that could be used instead
browsermob_ports_range=55881:55884

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/carina/pull/795
