### ISSUE TITLE
document new proxy range support in documentation

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#800]
https://github.com/qaprosoft/carina/issues/794

need adjust documentation on such pages:
http://qaprosoft.github.io/carina/configuration/
http://qaprosoft.github.io/carina/proxy/

[Sergei Zagriychuk]+ re-factor browsermob_host usage
I found that browsermob_host is a redundant parameter. Instead of it we can just override proxy_host property.

**Comment by okamara** [comment]
Verified.
