### ISSUE TITLE
integrate selenoid auto-download option into our artifacts verification

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#803]
For now to support verification of the auto-downloaded documents for the selenoid tests we have to provide machines where java+selenoid are used together with extra volume sharing setup.

Using below approach we could try to inject download from selenoid to local java machine using:
https://aerokube.com/selenoid/latest/#_accessing_files_downloaded_with_browser

**Comment by vdelendik** [comment]
https://sqa.stackexchange.com/questions/2197/how-to-download-a-file-using-seleniums-webdriver

good answer:
The best way I have found to do this is by accessing the page, getting the download link, and performing a HEAD request for the file with an HTTP library. The response will contain the length of the file and it's type.

A HEAD request is preferable since it will only retrieve the headers instead of pulling down the entire file.

And if the file is behind auth, you will need to pull the session cookie from Selenium's cookie store and pass it into the HTTP library when performing the request.

That, or you can configure the browser you're using to auto-download files to a specific location and then perform checks against the file on disk.

I've outlined each of these approaches in detail with working Ruby code here:

Browser specific configuration
Working in tandem with an HTTP library for secure files
Cheers,
Dave H
@TourDeDave

**Comment by ivansnytko** [comment]
#815
