### ISSUE TITLE
hide STF related messages to debug layer

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#824]
let's hide such message to debug layer as they not test specific and must be sued only by admins to setup STF+Appium integration.

STF is enabled. Debug info will be extracted from the exception.
Extracted debug info: DEBUG info: Error executing adbExec. Original error: 'Command '/opt/android-sdk-linux/platform-tools/adb -P 5037 -s UDID shell pm install -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk' ... Show more

Found parameter: udid -> UDID
Found parameter: name -> NAME

**Comment by ivansnytko** [comment]
#835
