### ISSUE TITLE
Add ability to change rqPath, rsPath, propertiesPath

### ISSUE THREAD

**Issue by leonpros** [qaprosoft/carina#825]
AbstractApiMethodV2 class should have relevant methods:
```
setRqPath(String rqPath)
setRsPath(String rsPath)
setPropertiesPath(String propertiesPath)
```

Mainly can be used for negative tests where the method class will be used for both functional and negative tests and the response/request can be modified during run (using dataproviders or code)

**Comment by KirillBugrim** [comment]
Resolved by https://github.com/qaprosoft/carina/commit/d8f900a75c44a3428f74b238bad7f76c90667b4d#diff-78bf25eb39d6c43e3a6acaabb9d7d63c

**Comment by vdelendik** [comment]
done
