### ISSUE TITLE
Make approach to instantiate Drivers more extendable 

### ISSUE THREAD

**Issue by aximus** [qaprosoft/carina#826]
Currently, I do not see an option to instantiate my own driver and pass it to carina. Is there a plan to make code extendable to let developers use their own Drivers?

For example, I would like to use EnhancedAndroidDriver<MobileElement> to be able to use carina with Xamarin (AppCenter) test cloud.

Thanks!

**Comment by vdelendik** [comment]
@aximus, we register extra listeners like video recording, event listener etc for each driver. Any examples how do you start EnhancedAndroidDriver, env where we can experiment...
I like the idea to make common interface which can be implemented/overrided on customs test layer...

**Comment by vdelendik** [comment]
closing as no extra information provided
