### ISSUE TITLE
Drag and drop for HTML5

### ISSUE THREAD

**Issue by nazarenkAV** [qaprosoft/carina#83]
Current drag and drop method doesn't work for HTML5 web apps.

Solution that I found:
WebElement exercise = getExerciseItem(name).getElement(); // what to drag 
WebElement dayBlock = getDayBlock(day).getElement(); // where drop
Actions act = new Actions(getDriver());
Action drag = act.clickAndHold(exercise).build();
drag.perform();
Point coordinates = dayBlock.getLocation();
Robot robot = new Robot(); 
robot.mouseMove(coordinates.getX()+20,coordinates.getY()-20);
pause(5000);

**Comment by vdelendik** [comment]
not actual anymore
