### ISSUE TITLE
zafira.properties: rename unavailable job to localhost

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#841]
**Describe the bug**
A clear and concise description of what the bug is, actual and expected behavior.

**Logs/Links**
If applicable, attach console logs to help explain your problem.
Note: make sure you don't attach any private content like credentials etc in logs.  

**Web (please complete the following information):**

**Mobile (please complete the following information):**
 - Appium version [e.g. 1.10.0]

**Additional context**

**Comment by ivansnytko** [comment]
Created ticket for zafira-client repository https://github.com/qaprosoft/zafira-client/issues/10

**Comment by vdelendik** [comment]
closing as changes should be done on zafira-client side
