### ISSUE TITLE
Bug ID of the newly created issue is not added to the test reports

### ISSUE THREAD

**Issue by SaleenaDavoodA** [qaprosoft/carina#843]
**Describe the bug**
Email generation starts in CarinaListener —> onFinish(ISuite suite) method. But onTestFinish(ITestResult result) we perform Jira.clearTickets(); That's why Jira num is not displayed in the report.

In AbstractTestListener —> createTestResult(ITestResult result, TestResultType resultType, String failReason, String description) —>  line testResultItem.setJiraTickets(Jira.getTickets(result)),  jira tickets should be parsed from result.getAttribute(SpecialKeywords.JIRA_TICKET)

**Logs/Links**
https://github.com/qaprosoft/carina/blob/master/carina-core/src/main/java/com/qaprosoft/carina/core/foundation/listeners/CarinaListener.java#L392

**Web (please complete the following information):**
 - Browser [Chrome]
 - Version [78.0]

**Comment by kolyakrasnik** [comment]
Currently all integrations are performing with Zafira. So, this logic should be moved to zafira level. There is a ticket to track the issue. https://github.com/qaprosoft/zafira/issues/1855
