### ISSUE TITLE
@CaseInsensitiveXPath doesn't work for some locators

### ISSUE THREAD

**Issue by khegor** [qaprosoft/carina#846]
@CaseInsensitiveXPath doesn't work for some locators such as : 
//android.widget.LinearLayout[./android.widget.TextView[contains(@text, 'someText')]]//*[contains(@resource-id, 'id/someId')]

Expected result: the text is converted to case insensitive mode
Actual: some parts of the locator converted with text. It looks like this : 

*** Element info: {Using=xpath, value=//android.widget.LinearLayout[./android.widget.TextView[contains(translate(@text, 'SOME_TEXT')]]//*[CONTAINS(@RESOURCE-ID, 'ID/SOME_ID', 'some_text')]]//*[contains(@resource-id, 'id/some_id'),translate('Some_text')]]//*[contains(@resource-id, 'id/some_id', 'SOME_TEXT')]]//*[CONTAINS(@RESOURCE-ID, 'ID/SOME_ID', 'some_text')]]//*[contains(@resource-id, 'id/id/some_id'))]}

 - Device: Samsung, Lg, HTC, OnePlusOne
 - OS: 6, 7, 8, 9 Android
 - Appium version [e.g. 1.15.1]

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/carina/pull/854
