### ISSUE TITLE
Parallel Execution on iOS And Android

### ISSUE THREAD

**Issue by pavanbachu06** [qaprosoft/carina#851]
**Describe the solution you'd like**
How to execute a single test case on Android and IOS in parallel

**Comment by vdelendik** [comment]
Hey @pavanbachu06!
1) TestNG doesn't allow to parallel single test method so there are 2 available scenarios:
a) single test method with 2 drivers. In this case you just use different capabilities for getDriver(...) call
https://github.com/qaprosoft/carina/blob/2fc50fb0435ff16722b295829185867bd8969787/carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java#L90
or
https://github.com/qaprosoft/carina/blob/2fc50fb0435ff16722b295829185867bd8969787/carina-webdriver/src/main/java/com/qaprosoft/carina/core/foundation/webdriver/IDriverPool.java#L106

2) you split your test case onto different methods or use dataprovider to reiterate the same case on different devices. In this case you can manipulate multi-threading by 
thread_count or data_provider_thread_count parameters and parallel="..." annotation in TestNG suite xml file.

Also pay attention that some improvements planned for 6.3.30 in threads usage:
https://github.com/qaprosoft/carina/issues/859

**Comment by vdelendik** [comment]
closing as not a bug but question as answer provided.
@pavanbachu06 ^^^
