### ISSUE TITLE
@CaseInsensitiveXPath doesn't work after update to the 6.2.29 version

### ISSUE THREAD

**Issue by slash2020327** [qaprosoft/carina#865]
The xpath doesn't work:
@CaseInsensitiveXPath
@FindBy(xpath = “//*[contains(@text, 'Quick Add')]“)
Also, annotation doesn't work with double quotes.

The exception log looks like:
The element of food more option menu is not found via locator: itemByTextCase (By.xpath: //*[contains(translate(@text, “QUICK ADD”, “quick add”),translate(“Quick Add”, “QUICK ADD”, “quick add”)])
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
org.testng.TestRunner.privateRun(TestRunner.java:648)
org.testng.TestRunner.run(TestRunner.java:505)
org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

 - Device: Samsung Galaxy S7
 - OS: 8.0.0
 - Appium version 1.15.1

**Comment by vdelendik** [comment]
fixes and unit tests are here: https://github.com/qaprosoft/carina/pull/877
