### ISSUE TITLE
Carina API properties file : Random string generation

### ISSUE THREAD

**Issue by ghost** [qaprosoft/carina#874]
Hi,
It is observed that when pass below format for string generation in any api properties file 
newpwd=Qgenerate_word(3)Pgenerate_number(2)generate_word(3)@generate_number(2) 
and fetch its value using
rspwd.getProperties().getProperty("newpwd");
it displays value as
QqslPgenerate_number(2)qsl@generate_number(2)

Same can be used to create random PAN number for any testing.

Value considered in API body was 'QqslP23qsl@23', which is as per random logic.

We need to capture random string generated. 
Options tried is 
1. Via getproperty
2. Search to fetch request body values
But not able to fetch it.

Please help to provide the logic where we can save output generated using more than 1 random data types.

**Comment by vdelendik** [comment]
fixed. change should be in 6.5.36+ carina
