### ISSUE TITLE
Empty screenshot in the last test step

### ISSUE THREAD

**Issue by mohamadli** [qaprosoft/carina#881]
Reproducible using Carina 6.2.29. 
When publish screenshots to Zafira instead of element with screenshot

&lt;i ng-show=&quot;log.isImageExists === false;&quot; class=&quot;material-icons&quot; aria-hidden=&quot;false&quot;&gt;insert_photo&lt;/i&gt;

is displayed.

How it looks in a test run:
![image](https://user-images.githubusercontent.com/47204765/71486606-40d93100-2828-11ea-9b5e-4f2f40533cf6.png)

The problem is not reproduced in each tests - I cannot detect correlation with test type or any other factor.

**Comment by vdelendik** [comment]
in 6.4.34 async operations should wait till latest screenshot is uploaded
