### ISSUE TITLE
Carina tracks an invalid version for the Opera browser

### ISSUE THREAD

**Issue by hursevich** [qaprosoft/carina#882]
Carina tracks an invalid version for the Opera browser: we track Opera v65.0 but getting Opera v78.0

**Logs/Links**
https://stage.qaprosoft.farm/app/tests/runs/897

**Web (please complete the following information):**
 - Browser: Opera
 - Version: 65

**Comment by vdelendik** [comment]
6.3.31-SNAPSHOT+

hotfix for Opera browser version detection applied: https://github.com/qaprosoft/carina/commit/fe6386c0ea5d2e71a1d0e19afb28843ed9b48c05

also submitted #915 for stronger refactoring vs all modern browsers
