### ISSUE TITLE
capabilities.browserVersion should be handled correctly to track browser_version

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#891]
need to update ZafiraConfigurator->getConfiguration()
For browser version it should work as for browsers, i.e. 
1) read from browser_version
2) read from capabilities.browserVersion
3) read from actual_browser_version

**Comment by okamara** [comment]
Web job is failed with errors.
<img width="1119" alt="Screen Shot 2020-01-21 at 6 21 27 PM" src="https://user-images.githubusercontent.com/32964663/72817545-02922e80-3c7b-11ea-9562-85c2d3bc39d8.png">
<img width="1065" alt="Screen Shot 2020-01-21 at 6 21 13 PM" src="https://user-images.githubusercontent.com/32964663/72817551-058d1f00-3c7b-11ea-9ea1-6e487f1257f9.png">

**Comment by okamara** [comment]
For Web job set:
1.
override field browser=IE
capabilities.browserName=chrome
capabilities.browserVersion=98
- Job is failed and chrome is set for zafira.
2. 
Set capabilities ->browserName=chrome;browserName=Safari;browserVersion=101
- Job is failed and Safari, version 101 is set for zafira.

**Comment by okamara** [comment]
Reverified
