### ISSUE TITLE
support locale/language appium capabilities generator for iOS

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#902]
in scope of a hotfix delivered locale/language caps generator for Appium/Android:
https://github.com/qaprosoft/carina/pull/901
https://github.com/qaprosoft/carina/pull/900

Let's investigate and deliver something common for mobile including iOS. The only problem is format of the arguments differs between platforms
![image](https://user-images.githubusercontent.com/4551455/73381257-76b17f80-42d6-11ea-9c1e-d3ebe685e28a.png)

**Comment by kolyakrasnik** [comment]
Related PR https://github.com/qaprosoft/carina/pull/983

**Comment by vdelendik** [comment]
merged to master.
feature should be available in 6.4.34+
