### ISSUE TITLE
Improve optimize video logic

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/carina#907]
Currently if optimize_video=true and retry_count > 0 we don't start recording video on attempt less then retry_count. So if we have retry_count=2 video recording will be started only on the last attempt and we'll lost the video in case of successfull tests execution during 0 or 1 attempt.
Idea is to start video recording every time, but don't publish the video if non-interesting attemp. If we have retry_count=2 and on the 1 attempt we have fail - we'll publish the video, but there is no sense in the video as far as zafira shows only the last attempt. 
As idea we can update MobileRecordingListener().beforeEvent(command) logic to publish video due to this logic ```ifDriverCommandQuit and ((isFailResult && try == retry_count) or isPassed)``` . So we will get videos for : passed test, failed test only for the last attempt. This will help us to use our disk space smarty.

**Comment by kolyakrasnik** [comment]
The changes are available in the branch https://github.com/qaprosoft/carina/tree/issue_907 and 6.3.696-SNAPSHOT

**Comment by vdelendik** [comment]
fix available in 6.3.31-SNAPSHOT+
feature: https://github.com/qaprosoft/carina/pull/912
