### ISSUE TITLE
Rerun failures doesn't work for 'depends on' logic

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/carina#908]
If we have test, which depends on another test rerun logic doesn't work.

**Comment by kolyakrasnik** [comment]
in case we use retry_count=0 rerun looks good. The issue occurs if we have retry_count=1.

**Comment by vdelendik** [comment]
fix available in 6.3.31-SNAPSHOT+
fixes: https://github.com/qaprosoft/carina/pull/912
