### ISSUE TITLE
refactor browser version detection using UserAgent info

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#915]
In scope of #882 hotfix applied only for opera browser.
During this enhancement let's review browser version identification logic for all other browsers as well.

in attach you can find UserAgent output based on browserstack browsers response. let's collect also from local selenium and other 3rd party hub providers to deliver strong browser version detection via UserAgent
[#882.xlsx](https://github.com/qaprosoft/carina/files/4177102/882.xlsx)

**Comment by kolyakrasnik** [comment]
Some helpful link https://stackoverflow.com/questions/5916900/how-can-you-detect-the-version-of-a-browser/38080051

**Comment by vdelendik** [comment]
valid driver detection should be implemented on reporting side. carina and her local report will show version provided in _config.properties
