### ISSUE TITLE
Add option to configure screenshots in Carina.

### ISSUE THREAD

**Issue by the-bmc-dev** [qaprosoft/carina#925]
**Describe the solution you'd like**
It will be nice to have an option to be able to configure the screenshots options in Carina.

**Additional context**
There are cases where you don't want a screenshot to be taken to the full page when a test fails, taking a full-page screenshot on pages that have sticky headers can result in an unusable picture.

Also, there are cases where do you want to take a screenshot of a specific element or content.

**Comment by vdelendik** [comment]
in 6.4 it is supposed to mograte onto the ISreenshotRule interface with ability to override everything

**Comment by vdelendik** [comment]
@the-bmc-dev: https://github.com/qaprosoft/carina/pull/1017
1) declared new "AutoScreenshotRule" rule to generate screenshots based on auto_screenshots property
2) reused Screenshot.captureByRule() for all optional screens capturing
3) declared global Screenshot.defaultCapturer and Screenshot.isEnabled()
4) disabled all carina screenshots rules even for failures using:
Screenshot.clearRules()

As result after calling "Screenshot.clearRules()" you have to 
1) manage capturing on your own completely based on rules.
2) use Screenshot.capture(...) methods to execute screenshots explicitly everytime

**Comment by mariushorvat** [comment]
@vdelendik do you have a sample how to implement Screenshot.clearRules()? Right now I have Screenshot.captureByRule() for all optional screens capturing but then if I add clearRules() method all my screenshots are cancelled, too.
