### ISSUE TITLE
bump up to 7.3.0 appium java client

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#936]
https://github.com/appium/java-client/releases/tag/v7.3.0

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/carina/pull/1036
6.4.37-SNAPSHOT+

**Comment by okamara** [comment]
@vdelendik could you please add more details to verify this ticket

**Comment by okamara** [comment]
Tested via https://github.com/qaprosoft/carina/blob/196a41f07e34fda74adbaf48934e9ecad7e90ddc/pom.xml#L52

**Comment by vdelendik** [comment]
it is recommended to test using android and ios job
