### ISSUE TITLE
Detecting elements in angularJS in IE is very slow. 

### ISSUE THREAD

**Issue by Vishyvarne** [qaprosoft/carina#937]
Detecting web elements in angularJS pages in Internet explorer driver is very slow. Issue is slowness is locating elements in dom. Though Carina locates the elements, it takes more than usual time. It takes around ~5 minutes to identify elements in a list of 200 items. While in chrome it works in 20 seconds.

Details: 
IE driver version : 32 bit IE driver server 
Selenium: 3.14.0

**Comment by vdelendik** [comment]
@Vishyvarne, you have to reuse valid version of IE driver 32 or 64bit to be in sync with OS. That's usually solve the problem of slowness.
