### ISSUE TITLE
Zafira results shows combined feature file instead of showing as separate/individual scenarios

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina#939]
1. suppose one feature file has multiple indepedent scenario .. then in zafira test run is showing result combined for all the scenarios in one run .. Can you tell me how to separate them ?

current feature file structure
abc.feature
  scenrio 1
    G
    W
    T
  scenrio 2
    G
    W
    T
  scenrio 3
    G
    W
    T

Runner has cucumberoptions : {abc.feature}
but in zafira result it is showing me 
test_run 1 : test_run > details > entire feature contents together (so unable to distinguish different scenario)

Run results in Zafira should be displayed like 
test_run 1 
    > test_run (feature description) : details  (Scenario 1) > detailed run steps of scenario 1
    > test_run (feature description) : details  (Scenario 2) > detailed run steps of scenario 2
    > test_run (feature description) : details  (Scenario 3) > detailed run steps of scenario 3

**Comment by vdelendik** [comment]
fixed in 7.0.0+
