### ISSUE TITLE
EventFiringWebDriver  cannot be cast to RemoteWebDriver

### ISSUE THREAD

**Issue by fengwenni** [qaprosoft/carina#943]
this doAttachFile function in ExtendedWebElement.java 

((RemoteWebDriver) getDriver()).setFileDetector(new LocalFileDetector());

java.lang.ClassCastException: org.openqa.selenium.support.events.EventFiringWebDriver cannot be cast to org.openqa.selenium.remote.RemoteWebDriver
	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement$1.doAttachFile(ExtendedWebElement.java:1569)

**Comment by vdelendik** [comment]
already fixed in 6.3.32+ carina
