### ISSUE TITLE
Implement java agent for Carina test running

### ISSUE THREAD

**Issue by brutskov** [qaprosoft/carina#952]
Custom java agent allow possibility to manage TestNG framework inner code, listener registration and run (basically).
(-) need to register java agent explicitly using VM options (from surefire plugin (maven), from test.doFirst task (gradle) or from run / debug configuration / VM options from IDE)

**Comment by vdelendik** [comment]
we are going to inject zebrunner agent via javaagent. it provides more functionality but might be rather cmplicated for local development purposes...
