### ISSUE TITLE
Support of local storage provider

### ISSUE THREAD

**Issue by victoriatco** [qaprosoft/carina#957]
Please add support of storage provider using local ftp for those who don't want to use amazon

**Comment by vdelendik** [comment]
we started to investigate possibility to use local s3-compatible local storage for screenshots/video etc artifacts.
Optimistically it should be available in May. Best candidate as of now is https://min.io/

**Comment by vdelendik** [comment]
already resolved in scope of zebrunner ce 1.0: https://github.com/zebrunner/zebrunner/releases/tag/5.2
