### ISSUE TITLE
override only auto_download folder

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina#970]
Hi Team, 
I am trying to save the some files in during the execution in chrome.
so I set below properties in that.
auto_download=true
custom_artifacts_folder=C:/Test/chromeDownloads/

File is getting downloaded in above given artifacts folder but with that there are two more folders are shown like server and CucumberReport.
Why this is getting downloaded there ? 
I think, It should not be available there. It should be inside the reports/qa/randomId/ folder ?
or  is there any way to disable it ?

**Comment by vdelendik** [comment]
@prasadjshimpi you can test new feature using below core build:
6.4.765-SNAPSHOT

new item for _config.properties:
auto_download_folder=NULL

After that only auto downloaded folders will be published to this location.
Changes expected to be available in upcoming 6.4.34 release build
