### ISSUE TITLE
Encryption/decryption not working

### ISSUE THREAD

**Issue by Vishyvarne** [qaprosoft/carina#987]
**Describe the solution you'd like**
Encryption and decryption of test data. 

**Additional context**
Encryption of test data with existing Crypto tool is not working. 

Expectation - feature to encrypt test data stored in test data properties file and while entering credentials in application - we need decrypt feature to decrypt test data and enter in login page.

**Comment by vdelendik** [comment]
@Vishyvarne, issue is fixed: https://github.com/qaprosoft/carina/pull/1008
change can be tested in 6.4.36-SNAPSHOT

6.4.36+

**Comment by Ashraf-Ali-aa** [comment]
@vdelendik this seems to be broken in carina 7.0.0, when I try to get the data via R.TESTDATA.get("test_credentials") it returns the encrypted data

**Comment by Ashraf-Ali-aa** [comment]
Managed to get it to work using `R.API.getDecrypted`
