### ISSUE TITLE
Unable to sent mail after execution from zafira if running test from Local machine

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina#999]
VD : Maybe we can provide access to notification end-point via zafira client. So on-suite finish you could send an email via code.

**Comment by vdelendik** [comment]
closing as won't fix. by default pipeline do this call via agent. To implement you could develop smtp class on your own or send api call to zebtunner/reporting at the end. Take a look to reporting swagger to identify required steps for that
